### ISSUE TITLE
DOC  "Documentation page not present"

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#1019]
#### Describe the issue linked to the documentation

If a page did not exist in the documentation of a previous release, there is message "Documentation not present", which looks a bit weird on the website. At the moment, this happens on almost every page of our website due to documentation missing for v0.4.6.

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/24417440/152387420-316d0d6a-b416-4e65-9899-2c3ba6f49180.png">

#### Suggest a potential alternative/fix

From the community call:
* Consider removing support/documentation from v.0.4.6.
* Change the message to something shorter.
* Change the behavior in some other way.

We also discussed adding warnings similar to scikit-learn in case you are not on the latest stable release.

Possibly also related to https://github.com/fairlearn/fairlearn/issues/874

**Comment by romanlutz** [comment]
FWIW the string change is super easy! It's hard-coded in our repo in this file: `docs/_templates/version-sidebar.html`
What would be a better string? Some perhaps not so great ideas:
- "Page added in later version"
- "Page did not yet exist"

Having a warning about not being on latest stable release is nice! Perhaps that could be solved in a separate PR, though.

I think dropping v0.4.6 may also be a separate PR. [The regex](https://github.com/fairlearn/fairlearn/blob/862263f4352e23da088ae7a638b88b56580e5230/docs/conf.py#L103) needs to be adjusted to exclude 0.4.6.
That PR should include removing special cases:
- https://github.com/fairlearn/fairlearn/blob/862263f4352e23da088ae7a638b88b56580e5230/docs/conf.py#L40
- https://github.com/fairlearn/fairlearn/blob/862263f4352e23da088ae7a638b88b56580e5230/docs/conf.py#L106
That may actually be all that's needed, but whoever tries this can validate the doc build, of course.
I'm personally looking forward to dropping 0.5.0 because we can drop the `bokeh` dev dependency after that 🙂 Long story...

I believe #874 is unrelated and more an issue with sphinx-multiversion that anything else (https://github.com/Holzhaus/sphinx-multiversion/issues/56).

**Comment by Hrittik20** [comment]
Hi @romanlutz, I would like to help fix this error. I think just writing "Later Version" would be short and simple.

**Comment by hildeweerts** [comment]
> FWIW the string change is super easy! It's hard-coded in our repo in this file: docs/_templates/version-sidebar.html
What would be a better string? Some perhaps not so great ideas:
> * "Page added in later version"
> * "Page did not yet exist"

If I remember correctly, the main issue that was raised during the call was the length of the message. We could consider simply not having any message at all, but that might be confusing as well... 

Thank you for the suggestion @Hrittik20! I'm not sure whether "Later Version" captures the message fully... but others might disagree.

> I think dropping v0.4.6 may also be a separate PR.

Agreed, we should probably open a new issue for this as well as 0.5.0.

**Comment by romanlutz** [comment]
How about just "N/A"?

I agree on creating separate issues for the removal of versions. That allows me to argue that 0.5.0 is too recent to remove, for example, without making this thread go off the rails 😄

**Comment by hildeweerts** [comment]
I like it! Let's do it :)

**Comment by romanlutz** [comment]
I'm a bit confused. I just checked the website and I don't see the N/A there.... Still shows the old string:
![image](https://user-images.githubusercontent.com/10245648/160444296-f904e03f-11de-4aa7-96ea-97645c3abb03.png)

The [website repo](https://github.com/fairlearn/fairlearn.github.io) looks like there have been no updates for 12 days. Perhaps something is broken in the website build. Let me look into that....

**Comment by romanlutz** [comment]
Update: CircleCI's deploy step failed. Rerunning right now to see if that fixes it:
https://app.circleci.com/pipelines/github/fairlearn/fairlearn/2658/workflows/b148e4aa-653b-4a6c-b6d8-29fc7a5f7888/jobs/5080

**Comment by romanlutz** [comment]
It started with #1046

**Comment by riedgar-ms** [comment]
Ahhh.... I see. The regular build pipelines are showing green, but the deployment pipeline (which only runs _after_ a merge isn't). And that's a spectacularly useless error:
![image](https://user-images.githubusercontent.com/28632930/160602817-78fd0914-9aed-4905-b659-c82ff3b60da9.png)

**Comment by romanlutz** [comment]
I'm guessing something is missing in that image that was there in the previous one resulting in the failure of npm install (?) 

We could copy some of the steps from deploy to build so that they are run in a PR. Except for the actual deployment, of course.

**Comment by romanlutz** [comment]
I'm not 100% sure what happened here since it's been a year almost. The original feature request to have "N/A" was completed. We since switched to no longer using `sphinx-multiversion` so it's only really shown in the older versions. I'm going to close this since there's nothing left to do.
