### ISSUE TITLE
BibTex reference styles

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#1048]
We have had significant conversations on how to references single articles on https://github.com/fairlearn/fairlearn/pull/1032 and https://github.com/fairlearn/fairlearn/pull/1044, and I'm not happy about how much effort has been going into how the reference and their IDs should look like.

I personally think we should allow contributors to copy/paste from wherever they want. As long as a reference is find-able by readers by the information we render on the website, we've achieved the goal of "providing a reference".

It seems a few of the @fairlearn/fairlearn-maintainers have strong feelings about how the entries in the bibtex file should look like. I would like us to discuss this, find a specific set of guidelines which don't put much burden on the contributors, and document it, so that next PRs touching references don't involve such discussions.

**Comment by romanlutz** [comment]
I agree on not wasting much time on this. That said, I feel like there's no particular point in adding lots of information with the reference that isn't actually rendered. The entire abstract, for example, seems like a bit much for my taste. This isn't a hill I'm willing to die on, though, which is why I'll (hopefully?) just watch the rest of this thread and upvote others' messages.

**Comment by adrinjalali** [comment]
I had a ton of those abstracts in my PhD thesis, because I didn't want to bother removing them. I don't want contributors to have to think about what fields to include and what not. The whole point of having a bibtex is to think about references less, not more.

**Comment by romanlutz** [comment]
[Now I'm already breaking my promise not to respond.... 😄 ]
PhD thesis != website
Most importantly, it's just one person working on it. In this case, I'd argue the other way round: if I'm a new contributor and I see that other references have abstracts and mine (from wherever I copied it) doesn't have the abstract I might even feel like I have to now go and copy this manually from a paper. Deleting a single line doesn't hurt me...

Also, the point of bibtex (at least for me) is to avoid repeating references. The first time I'm adding one I very much still read it, though. After all, I'm sure you're aware of how many of these have mistakes in them (benign ones or otherwise...).

**Comment by MiroDudik** [comment]
When it comes to bibtex entries, the only point that I actually feel strongly about is a naming convention for bibtex ids. I'm  strongly in favor of sticking with the format `<4digit-year><author-last-name><keyword>` where in the vast majority of cases, keyword is the first word of the title that is not an article or a conjunction.

I have some opinions about the rest of the bibtex entry--but those are more of recommendations (although I'd be happy to elevate them if others supported them):
1. don't cite arXiv/preprint if a peer-reviewed version exists
2. provide URL whenever possible
3. ensure that the references are rendered somewhat consistently (it's weird if some papers are from ICML while others are from Proceedings of the 15th International Conference on Machine Learning; it's weird if some papers list volume editors and others don't, etc.)

I agree with @romanlutz that any existing content of the bibtex file works as a template for future contributions, so it somewhat matters. I could see rationale re. removing some meta-information fields--I always remove them from my own bibtex entries--but I don't feel too strongly about this. 

Also: I don't think that asking contributors to make simple tweaks in their bibtex entries is creating too much friction -- compared with everything else that we are asking contributors to do, these are super easy. That's why I wouldn't be opposed to establishing something like "house style" (e.g., go with condensed DBLP with URL from standard DBLP), but--if I'm reading the crowd correctly--this is not something that we want to do? (Again I don't feel too strongly about this, but it would be good to decide what the rules are.)

**Comment by hildeweerts** [comment]
For me the bibtex ids are the only important part, because it makes writing texts and reviewing PRs easier and could possibly avoid some duplicates. 

Other than that I do agree with @MiroDudik's 3 recommendations, but those are of lower priority to me and I'm happy either way.

**Comment by MiroDudik** [comment]
@fairlearn/fairlearn-maintainers: it seems that @hildeweerts and I are in agreement that we should enforce some naming convention re. bibtex ids, and maybe provide some recommendations re. the rest, but neither of us feel too strongly about those recommendations. what do you think?

There's one issue that I'm seeing in #1044--the bibliography is rendered with multiple URLs per item shown? I personally find it confusing--so I'd just prefer showing one URL--this could be easily fixed by removing some metadata (or fixed more systematically by creating a new style... not sure we want to go that route). Is this the type of thing that we can handle on one-off basis, or shall we make a policy not to pester contributors about stuff like this?

**Comment by riedgar-ms** [comment]
I think that we should be encouraging people to copy/paste BibTeX entries from ACM Library/arXiv/wherever with minimal edits. That way they know they don't need to add the `abstract` field if it's not already there. And if people didn't already know that these places provide the BibTeX snippets, then we get the warm feeling that we have taught them something useful.

I agree that the entries should be edited to use spellings that the authors prefer for their names. Generating new citation keys seems pointless (and potentially storing heartache for the future) but tolerable. However, deleting fields from the copy/pasted entries because we don't like how they get rendered is subverting the whole point of BibTeX. That is a problem which should be solved in the `.bst` (or whatever the Sphinx equivalent is), and if we don't care enough to fix it there, then I say that _we don't actually care about it_.

All that said, if I'm not interacting with it much, I'm not fussed about the colour of the bike shed.

**Comment by MiroDudik** [comment]
@riedgar-ms -- agreed that we should minimize frictions. The issue with bibtex ids is that they impact usability of writing docs and hence I feel more strongly about enforcing a naming convention. Am I reading you correctly that you are fine with that?

**Comment by MiroDudik** [comment]
Also -- I'm assuming it's okay if I occasionally clean up the bibtex entries of the "offensive issues" that nobody besides me cares about :-)... Basically, I want to make sure that we don't cargo-cult whatever ACM Library/arXiv/DBLP chose for their bibtex entries (which is often driven by other concerns... like ease of automatic generation of webpages etc.).

**Comment by riedgar-ms** [comment]
As I said, ultimately, I don't care about the bike shed.

**Comment by hildeweerts** [comment]
I don't know what "cargo-cult" means (Google search was not very helpful), but as long as you don't bug our contributors about it, you have my blessing to alter the bibtex entries as much as you like, @MiroDudik! ;)

**Comment by MiroDudik** [comment]
@hildeweerts : https://en.wikipedia.org/wiki/Cargo_cult

**Comment by romanlutz** [comment]
This is a satisfactory resolution for me, too, and I nominate @MiroDudik for Chief BibTex Officer 🤣 It comes with a badge that you have to create in TikZ first.

**Comment by adrinjalali** [comment]
So I suppose we can close this one? The resolution seems to be copy/pasting from wherever we find the entries and only changing the IDs, and let @MiroDudik cleanup after the fact (not in the PR reviews) if certain things are there that he doesn't like? :D

**Comment by hildeweerts** [comment]
Agreed @adrinjalali ! I will close this now, feel free to reopen if you still have issues @fairlearn/fairlearn-maintainers
