### ISSUE TITLE
exposure metric ranking metrics #974

### ISSUE THREAD

**Issue by mnalk** [fairlearn/fairlearn#1068]
https://github.com/fairlearn/fairlearn/pull/974/files

Hi! I'm interested in ranking and fairness too. I like the example and scenario for the exposure metric. Unfortunately, I have no experience with how to put these files together from different branches. I have been trying for days, and I keep getting the same errors.
My question specifically is how to make the plot ranking work? If there is something I missed, like a notebook that explains how this metric works, I mean this one(https://dl.acm.org/doi/10.1145/3219819.3220088), I would appreciate guiding me through that code.

Here are the errors:

(mn) C:\Users\MN\exp\fairlearn\examples>python plot_ranking.py
Traceback (most recent call last):
File "C:\Users\Mn\exp\fairlearn\examples\plot_ranking.py", line 10, in
from fairlearn.metrics import exposure, utility, proportional_exposure
ImportError: cannot import name 'exposure' from 'fairlearn.metrics' (C:\Users\Mn\Anaconda3\envs\dana\lib\site-packages\fairlearn\metrics_init_.py)

I'm referring to this part here https://github.com/fairlearn/fairlearn/pull/974/files

I did the following :
1)conda install -c conda-forge fairlearn
2)git fetch origin pull/974/head:tempbranch
3)git checkout tempbranch
 it didn't work. Then Roman Lutz advised me to fork @bram49's fork of Fairlearn from where he created the pull request, and it's not working either.

I have no other experience to make this repo work. Any sugesttion please 

Thank you,
Mn

**Comment by romanlutz** [comment]
Hi @mnalk ! To use code from the version you can install from PyPI you'll have to wait a little while because #974 is not merged yet, which means it needs to get merged and then we need to do a release. I can't give you a timeline for either of those since both of these happen when it makes sense rather than "by deadline."

You can, as I mentioned in the PR comment, check out branches locally. This includes @bram49's PR branch that he created on his fork. You don't need to do a `conda install` or `pip install` for this because that would pull in a version from conda-forge or PyPI, respectively, neither of which have this change for the reasons described above. Instead, you'd have to get the branch locally and install `fairlearn` in editable mode. I would use the following commands for that:

```
git clone https://github.com/fairlearn/fairlearn.git
git remote -v
```
This should tell you that you have 1 remote called origin and it points to the URL in that command. Then:
```
git remote add bram49 https://github.com/bram49/fairlearn.git
git remote -v
```
Now you should have another one aliased `bram49` (after the user). For good measure let's fetch from there:
```
git fetch origin
git fetch bram49
```
Now your local git repo should be aware of all the branches there.
```
git checkout <branch>
```
where `<branch>` should be replaced with the PR branch. In the PR view I see this:
![image](https://user-images.githubusercontent.com/10245648/163700977-8505b7a2-66a8-4696-a119-393e0d5a734f.png)

which tells me that his branch name is `fairlearn#959` (which is a bit funny since the PR number is not 959, but I'm sure @bram49 had his reasons 🙂 ).
That command should tell you that you are now locally on a branch that mirrors the remote one in @bram49 's repo. Voila, you did it!
Now you just have to install `fairlearn` so that you see these changes locally.
```
pip install -e .
```
Alternatively, if you won't change the code at all, you can also not put `-e`, that's for editable.

If you have any issues with this please post a full set of outputs for every command that you've run so that it's easy to see what went wrong. Thanks!
