### ISSUE TITLE
Cannot use estimators that do not require sample_weights with ExponentiatedGradient

### ISSUE THREAD

**Issue by Teddyzander** [fairlearn/fairlearn#1087]
#### Describe the bug
Cannot create an in-learning minimisation problem using ExponentiatedGradient and MLPClassifier.

The problem lies in __lagrangian.py_. The function __call_oracle_ insists on passing sample weights to the .fit function of whichever model is passed to it, but not all learning processes require a sample weights array. This causes some models to throw a type error when trying to fit the data to a model.

A simple fix would be to

a) Put in an except clause, so
```
try:
    estimator.fit(self.constraints.X, redY, **{self.sample_weight_name: redW})
except:
    estimator.fit(self.constraints.X, redY)
```
or b) let the user pass a sample_weights_name = 'none' into the function, and surround with an if else statement.

I think the default behaviour is to weight all the samples as 1.

#### Steps/Code to Reproduce

1. Create any data set with input features, outputs, and a sensitive field.
2. Create an instance of ExponentiatedGradient using the MLPClassifier as the model
3. Attempt to train on the data set

```
import numpy as np
from sklearn.neural_network import MLPClassifier
from fairlearn.reductions import DemographicParity, ExponentiatedGradient

input = np.random.rand(5, 5)
output = np.array([1, 1, 1, 0, 0])
sens = np.array([1, 0, 0, 1, 1])

model = MLPClassifier(solver='lbfgs', alpha=1e-5,
                      hidden_layer_sizes=(16, 8, 4, 2),
                      max_iter=1000, random_state=123)

model = ExponentiatedGradient(model, constraints=DemographicParity(), eps=0.01, nu=1e-6, max_iter=50)

model.fit(X=input, y=output, sensitive_features=sens)
```

#### Expected Results

Should use the selected fairness constraint to train a multi-layer perceptron 

#### Actual Results

Throws a type error on line 175 in __lagrangian.py_

#### Versions
- OS: 10
- Python version: 3.9.12
- Fairlearn version: 0.7.0
- version of Python packages: numpy 1.21.5, scikit-learn 1.1

**Comment by romanlutz** [comment]
Hi @Teddyzander, I'm afraid the entire point of `ExponentiatedGradient` is to pass sample weights, otherwise it has no chance to reweight samples which is at the core of what it does to reach the specified conditions (e.g., demographic parity). In essence, you wouldn't really achieve your goal. You may want to look into other mitigation techniques instead.

CC @MiroDudik @riedgar-ms

**Comment by Teddyzander** [comment]
Hi @romanlutz, thanks for the response. I did think this might be a problem with scikit learn, not Fairlearn! No worries, thanks for the explanation.

Some other MLP packages use sample weights, so I'll try them out!

Thanks

**Comment by romanlutz** [comment]
I definitely agree that that's one way of looking at it 🙂 
You may find the discussion in #4 interesting. We considered adding a wrapper for estimators that don't provide `sample_weight`, but it's not really a Fairlearn functionality since it's much more broadly applicable. That workstream is pretty much dormant and waiting for someone to pick it up. 

Can we close this issue @Teddyzander or is there anything else regarding this point? For other questions/problems please open new issues 🙂

**Comment by Teddyzander** [comment]
@romanlutz all good here, happy for you to close this issue. Thanks again

**Comment by Teddyzander** [comment]
Just for completeness though, I'll add [this issue from scikit learn](https://github.com/scikit-learn/scikit-learn/issues/9113)
