### ISSUE TITLE
CI update / delete nightly build pipelines

### ISSUE THREAD

**Issue by MiroDudik** [fairlearn/fairlearn#1180]
We currently don't have any nightly builds, do we want to reinstitute them?

Related items:
* It's probably safe to delete devops directory (which was previously used for nightly builds and Azure Pipelines more broadly)
* Azure Pipelines sticker in our readme should be deleted too

**Comment by MiroDudik** [comment]
Related issues: #965

**Comment by romanlutz** [comment]
Nightly builds used to be more comprehensive. I think that's still the case, @riedgar-ms ?
The problem is the Azure Pipelines org is weirdly orphaned and @riedgar-ms and I tried on several occasions to get it back, but so far unsuccessfully. We could, of course, set up a new organization, but that seems backwards since we'd rather have everything on GH Actions. That, in turn, wasn't possible in a simple way so far because GH Actions doesn't support extensive templating the way Azure Pipelines does. That doesn't mean it's not possible to do this, it would just mean a significant amount of redundant setup code (unless we spend time rewriting it into scripts).

People (myself included) have faced issues with those templates in the past as it's complicated to understand what's really going on when the commands are distributed over 7 different files. In that sense, one might argue that it's preferable to have some redundancy but it's all in one file.

With that context, we should probably analyze what the nightly builds have that the normal PR gates don't have and consider setting it up on GH Actions. I'm certainly for that, but I'm curious what other people think, particularly @fairlearn/fairlearn-maintainers as they deal with these issues the most. 🙂

**Comment by riedgar-ms** [comment]
I believe that the part that's missing in the GitHub actions is the "Nightly Fixed" build, which pinned dependencies to their lower bounds.

**Comment by romanlutz** [comment]
Got it! Any thoughts on migrating to GH Actions? Let's say 
- 🚀 means "go for it" and 
- 😕 means "nah, let's set up Azure Pipelines again, I like the templating"

**Comment by romanlutz** [comment]
It appears @adrinjalali already made a huge step towards this in #1080. This is awesome! I'll see what's missing...
