### ISSUE TITLE
Link to "main" on the documentation website throws 404

### ISSUE THREAD

**Issue by VladimirShitov** [fairlearn/fairlearn#1349]
#### Describe the bug

On the website, there is a list of versions of the package:
<img width="419" alt="image" src="https://github.com/fairlearn/fairlearn/assets/35199218/df0e2104-1a54-496c-abb2-f320474ff488">

They seem to work fine, except for the "main" one. When I click on it, the 404 error is thrown:
<img width="1227" alt="image" src="https://github.com/fairlearn/fairlearn/assets/35199218/6e9a0cc5-0f2c-42ac-b563-d3ad3111b32d">

#### Steps/Code to Reproduce

I started at the [metrics page](https://fairlearn.org/v0.7.0/api_reference/fairlearn.metrics.html). Just click on "main" in the versions section.

**Comment by hildeweerts** [comment]
Hi @VladimirShitov. Thank you for opening an issue! This occurs because we've changed the structure of the API docs since v0.7.0. As a result, there's no longer a separate page for the metrics module, resulting in the error. If you're interested in the API reference for main, I'd starting at the index:  https://fairlearn.org/main/api_reference/index.html
