### ISSUE TITLE
Confidence intervals for equalized odds

### ISSUE THREAD

**Issue by egistific** [fairlearn/fairlearn#1443]
Hi,

Is there a function that can be used to compute the confidence intervals for the fairness metrics such as demographic parity ratio and equalized odds ratio in https://github.com/fairlearn/fairlearn/blob/main/fairlearn/metrics/_fairness_metrics.py?

Thank you.

**Comment by hildeweerts** [comment]
Hi, @egistific! I recommend having a look at the various methods of our `MetricFrame` class which have "_ci" appended. For example, we have a method [`fairlearn.metrics.MetricFrame.difference_ci`](https://fairlearn.org/v0.11/api_reference/generated/fairlearn.metrics.MetricFrame.html#fairlearn.metrics.MetricFrame.difference_ci), which returns bootstrapped confidence intervals. 

So to get a confidence interval for e.g. demographic parity difference, you can build a MetricFrame including `fairlearn.metrics.selection_rate` as one of the metrics and compute a CI for the maximum difference in selection rates between groups. Note that this does not work for equalized odds, because that specific metric takes the maximum of two maximum differences (the true positive rate difference and false positive rate difference), but you can of course still compute the CIs for TPR difference and FPR difference separately. 

See also [this section](https://fairlearn.org/v0.11/user_guide/assessment/confidence_interval_estimation.html) of the user guide. I hope this helps!
