### ISSUE TITLE
Documentation - argument types

### ISSUE THREAD

**Issue by riedgar-ms** [fairlearn/fairlearn#254]
Our documentation:
https://fairlearn.readthedocs.io/en/latest/index.html
does not consistently provide links to definitions of Estimators (which should come from `sklearn`), `numpy.ndarray` and `pandas`. These should be remedied.

**Comment by adrinjalali** [comment]
could you maybe post an example of what you want to see changed?

This may also be helpful as a guideline: https://scikit-learn.org/dev/developers/contributing.html#guidelines-for-writing-documentation

**Comment by riedgar-ms** [comment]
As an example, at the time of writing:
https://fairlearn.github.io/api_reference/fairlearn.postprocessing.html
In the documentation for the `X` argument of the `fit()` method, there is a link to the pandas DataFrame documentation, but not the numpy ndarray doc.

**Comment by romanlutz** [comment]
I grouped this under doc infrastructure since sphinx should throw warnings for this kind of problem. I think @riedgar-ms enabled warnings for similar things recently. Perhaps we can iterate on this. If anyone feels like going through the remaining issues that would be awesome to clean up. This is definitely related to #314 as well since the change in format may affect some of these things.

**Comment by romanlutz** [comment]
This issue is too broad. I've fixed dozens of these little problems all over the code base (most recently #861), but if we want people to contribute in fixing these we need to create little and actionable issues. For example, whenever you stumble upon something that doesn't render properly open an issue and mention exactly where you encountered it (with screenshot and link) and what you expected (and perhaps how one might go about fixing it).

I know there are still plenty of doc build warnings that I haven't gotten to but there's also another related issue. I'm closing this one since it won't gain traction as is.
