### ISSUE TITLE
Release versioning

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#258]
We currently push a version to test pypi with `dev0` appended, and then another one to pypi. See

https://test.pypi.org/project/fairlearn/#history
and
https://pypi.org/project/fairlearn/#history
for examples.

@adrinjalali has proposed to simply do a rc release to pypi, and once it's stable release without rc. If there are still issues then release with patch. Let's use this thread as a discussion forum.

At the end we need to update the documentation (CONTRIBUTING.md) accordingly.

**Comment by riedgar-ms** [comment]
Do you mean to remove Test PyPI from our release pipeline, and always just push RC versions to PyPI?

The problem that the `.dev[n]` suffix is solving (and I believe it [can be combined with RC](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers)) is that PyPI doesn't separate 'upload' from 'publish'. I always want to push exactly the same changeset to Test PyPI and PyPI, and that merging of upload and publish means that we can 'burn' versions in Test PyPI. So automatically adding the `dev[n]` suffix to Test PyPI sidesteps the issue.

**Comment by adrinjalali** [comment]
Could you maybe elaborate @riedgar-ms ? I'm not sure if I understand.

**Comment by riedgar-ms** [comment]
Basic idea is that we have a release pipeline which takes a changeset, runs tests, releases to Test-PyPI and runs tests on that, and then finally releases to PyPI itself.

Suppose we don't have the `.dev[n]` mechanism, and we're trying to release v1.0.0. This gets to Test-PyPI and we have a problem. So we fix it. But now, we can't release v1.0.0 to Test-PyPI again... we have to go with v1.0.1. And that's the version which will ultimately go to PyPI itself. In a nutshell, the version released to PyPI depends on the number of issues we found at the Test-PyPI stage.

So by dynamically adding `.dev[n]` to the Test-PyPI versions (where `n` is specified at the time the release is created) we can bypass this.

Does that make sense?

**Comment by romanlutz** [comment]
I think @adrinjalali is trying to say that you can release v1.0.0-rc0. Doesn't work? Release v1.0.0-rc1, etc. until one finally works as expected. Then release v1.0.0
That's at least how most projects I've seen handle it.

**Comment by adrinjalali** [comment]
> Basic idea is that we have a release pipeline which takes a changeset, runs tests, releases to Test-PyPI and runs tests on that, and then finally releases to PyPI itself.

I'm not sure why you need to upload to `test.pypi` to run the tests. The artifacts can be created and tested in the same pipeline w/o having to upload them anywhere. Another solution is if you really need a staging area, you can do what the scipy ecosystem does, which is to upload them somewhere else first. We used to have an account on rackspace, and have moved now to anaconda.org. You can check this org to see how it looks and see the files we're uploading there: https://anaconda.org/scipy-wheels-nightly . We also upload our nightly builds on that repo and give instructions on how to install the nightly from there on our website.

Regarding the `dev[n]`, you can do `rc[n]` instead, which is what we do as well. In worst case scenario, if there's a very minor issue in your release and you'd like to fix it, you can release a `.post[n]` version. We had to do it in our latest release since we forgot to exclude some `.c` files from the wheel.

**Comment by riedgar-ms** [comment]
Now you mention it, the AzureML SDK packages do have another internal archive for their pre-release packages, so perhaps the actual upload to Test-PyPI isn't required. Burning versions there is what prompted the `dev[n]` workaround. The key point (as you note) is to test the actual package, well apart from the repo.

Side note: I did have Test-PyPI have `rc[n]` for a while, but decided to change to `dev[n]` since that's "less significant" and can actually be combined with `rc[n]`.

I do want to avoid something that happened to one of our dependencies (specifically, _nested_ dependencies, so hunting it down wasn't fun) a few months ago, where in the morning they release v4.0.0 .... and by the end of the day, they were up to v4.0.4 and finally managed to get it right.

If we change our release pipeline to do the install-from-local (or perhaps from a storage account) instead, I'd be happy to drop Test-PyPI. Perhaps that would be something to investigate in GitHub Actions @romanlutz ?

**Comment by romanlutz** [comment]
I'm always for GitHub Actions, as you know. However, that means every step of that pipeline would have to be moved over, and since the validation is part of that, all of that, too. That validation includes all our tests AFAIK, so it basically means moving over everything.

**Comment by riedgar-ms** [comment]
Closing this in favour of:
https://github.com/fairlearn/fairlearn-proposals/pull/11
There have also been changes to the release pipelines, removing the `.dev[n]` suffix.
