### ISSUE TITLE
RFC: have benchmarks instead of/on top of current perf tests

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#278]
Currently the performance tests are benchmarks which are supposed to be run on azure-ml. There are two issues with this:

- most people don't have an azure-ml subscription, and the results are not public.
- running the benchmarks independently is kinda impossible, and it's cryptic code which I'm not sure where I'm supposed to extract the actual benchmark from. I guess `script_generation.py`?

I'm also not sure if they're tests, they/it seems to be a benchmark, but I may be missing something.

If it's not a test suite which is run by people who are going to package the lib, should it be moved to a benchmark folder instead maybe? And have standalone `.py` files which do the tests locally?

p.s. I was gonna check the performance and experiment with `numba`, and benchmarks seemed like a good place to start.

**Comment by romanlutz** [comment]
It's a matrix of test cases with a lot of redundant code, which is why it is the way it is. Nobody would want to run the entire matrix on their machines because it would take hours. If you have a good suggestion I'm happy to add a step to publish the results somewhere (automatically after every run). A simple solution would be to put them in a publicly accessible blob, but that doesn't sound like it's easy to consume either. 

One thing to make this easier for people who don't have an azureml workspace is to provide an option to just generate the scripts and then not run them in azureml. That would allow running them locally then.

**Comment by adrinjalali** [comment]
Since it depends on azure-ml sdk thingy, WDYT of moving it to its own repo, and instead having a few benchmarks on the main repo?

Generating the scripts is also a good start.

**Comment by romanlutz** [comment]
I'm not opposed to that at all. If you have any other kinds of benchmarks you want to run without azureml, feel free to add a separate directory for that. We can also rename the existing one from perf to perf-azureml until it's moved out in case you want to use "perf" for yours.

**Comment by adrinjalali** [comment]
Just a note that if we move this forward, I'd be able to work on the performance issues using `numba` ;)

**Comment by adrinjalali** [comment]
Closing this one since the perf tests are moved away from this repo. We can have specific issues on benchmarks if needed in the future.
