### ISSUE TITLE
ThresholdOptimizer as a scikit-learn meta-estimator

### ISSUE THREAD

**Issue by adrinjalali** [fairlearn/fairlearn#308]
`ThresholdOptimizer`'s current implementation looks like a meta-estimator, but does not implement it as meta-estimators are implemented in sklearn.

One of the issues right now, is that it implements two different cases, one is when the child estimator is already fitted, one is when it's not.

As mentioned in https://github.com/fairlearn/fairlearn/pull/282#discussion_r377255359

> Sorry for a delay on this, but I think that `warm_star` is confusing in this context.
> 
> Just to state the obvious: the high-level semantics of `ThresholdOptimizer` (after it is fitted) is really of a two-stage pipeline. The first step is implemented by `self._estimator.predict()`. It takes as input `X` and returns `y`. The returned `y` is then transformed into `y'` (inside `self.predict()`).
> 
> We would like to enable two styles of fitting this pipeline: (1) fitting both steps from the provided data; or (2) fitting only the second step from the provided data (and using the provided `unconstrained_predictor` as the first step). Now if I think about a warm start, I would expect re-fitting a previously fitted pipeline, using the previous pipeline as a warm start. This to me is quite different from (2), which is just fitting the second stage of the pipeline (from scratch) while keeping the first stage of the pipeline untouched.
> 
> I'm not quite sure I understand the issue with the interaction between the cloning behavior and the `unconstrained_predictor` argument.

This makes it tricky to have a usual sklearn meta-estimator, since cloning the estimator (`ThresholdOptimizer` in this case) does not keep the fitted child estimator. For example, `Pipeline`:

``` python
In [1]: from sklearn.pipeline import Pipeline                   

In [2]: from sklearn.svm import SVC                              

In [3]: from sklearn.datasets import make_classification

In [4]: X, y = make_classification()

In [5]: clf = SVC().fit(X, y)

In [6]: Pipeline([('svm', clf)]).predict(X)
Out[6]: 
array([..., 0, 1, 1])

In [7]: from sklearn import clone

In [8]: clone(Pipeline([('svm', clf)])).predict(X)
...

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

```

And that's important since `GridSearchCV` would `clone` the estimators before fitting them.

Another point regarding `warm_start`, is that right now the user has to call `fit` even if the given estimator is pre-fitted. In `sklearn`, we usually assume `warm_start` means the user has called a fit on the estimator already; but here we could use it with a different meaning and assume that the user has passed a pre-fitted estimator. The `warm_start` semantics of sklearn are not very well-defined anyway, and we're still working on them.

__EDIT__

So my proposal is to implement a usual meta-estimator as is in sklearn, and include the `warm_start` parameter to support a pre-fitted estimator.

WDYT @MiroDudik @romanlutz

**Comment by MiroDudik** [comment]
Thanks for explaining the cloning behavior!

My only issue with your proposal is the name `warm_start`. It's not just that it somewhat mismatches how it's used elsewhere in `sklearn`, it also does quite match what I'd expect.

I am fine with two options:

* *less preferred*: Always fit the estimator when calling fit on `ThresholdOptimizer` instance. This would drop our old functionality for now, but we can add it back in future.

* *more preferred*: Keep the ability to provide a fitted base estimator, but let's not use `warm_start=True` as a flag, but use some other keyword. I'm happy to use something like `prefitted_estimator=True` or just `prefit=True`. This would be analogous to running `CalibratedClassifierCV` with `cv='prefit'`.

I can think of two reasons why use a prefitted estimator:

* Scale: The base estimator may be fitted on a much larger data set than the threshold optimizer, so we don't want to spend a lot of time on fitting the base estimator over and over if we are only exploring different fairness criteria in the threshold optimizer (such exploration would have to be manual rather than inside `GridSearchCV`). Also, statistically speaking, to get a high-quality threshold optimizer requires much less data than getting the initial high-accuracy predictor.

* Availability: We may only have access to the base estimator, but not to the data it was fitted on, e.g., for data privacy reasons.

**Comment by adrinjalali** [comment]
>  * _more preferred_: Keep the ability to provide a fitted base estimator, but let's not use `warm_start=True` as a flag, but use some other keyword. I'm happy to use something like `prefitted_estimator=True` or just `prefit=True`. This would be analogous to running `CalibratedClassifierCV` with `cv='prefit'`.

Yes, we could do that. We could even keep the `prefit` name in the interest of keeping the names short. However, we need to document that it's only a preference, and even with `prefit=True`, the estimator will do a `fit` on the child estimator.

>  * Scale: The base estimator may be fitted on a much larger data set than the threshold optimizer, so we don't want to spend a lot of time on fitting the base estimator over and over if we are only exploring different fairness criteria in the threshold optimizer (such exploration would have to be manual rather than inside `GridSearchCV`). Also, statistically speaking, to get a high-quality threshold optimizer requires much less data than getting the initial high-accuracy predictor.
> 
>  * Availability: We may only have access to the base estimator, but not to the data it was fitted on, e.g., for data privacy reasons.

I'm not opposed to having the `prefit` option, but both of these can be achieved w/o the `prefit` option, using a `FrozenEstimator`. You can see the discussion in https://github.com/scikit-learn/scikit-learn/issues/13288 and my implementation of it here: https://gist.github.com/adrinjalali/de9ac56c61f3931b38b24e577f54d083

**Comment by MiroDudik** [comment]
Great! Let's implement the `prefit` option then and put in a disclaimer similar to:
https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectFromModel.html
