### ISSUE TITLE
Purpose of FairLearn with AIF360

### ISSUE THREAD

**Issue by firmai** [fairlearn/fairlearn#311]
What do you see as the purpose or future of FairLearn with AIF360 gaining support? Advantages, disadvantages and the like.

**Comment by adrinjalali** [comment]
As somebody who's not a member of either of the teams and has contributed to both of them, I believe there's value in having multiple teams working on the topic.

I do worry about the community aspect of AIF360 though. IBM seems very protective of their branding and ownership when it comes to the governance of the package, and that may hurt them in the long run (at least it has discouraged me to spend more time on it than I do).

If there were no company politics involved, in an ideal world, I'd be delighted to see a unified effort on a single package with an open governance model. But unfortunately we don't live in that world.

And that's quite aside from the technical differences and that they implement different methods. As the FAT-ML community works on the topic and advancements are made, it'd be nice to have the methods available to a broader community for us to see the feedback, what works, and what doesn't in practice. The sheer number of methods itself would require more workforce as either of these groups (aif360 and fairlearn) have available.

**Comment by MiroDudik** [comment]
Excellent question. I'm one of the folks that started the project. As @adrinjalali mentioned, our hope is to be truly open and collaborative. We are currently figuring out the right model of governance, so that we can make this happen. Feel free to share on this issue if you know of governance models that you think would work well (as we're starting small, but generate decent community interest).

On a high level, we firmly view fairness as a socio-technical challenge, so we want to provide techniques that enable humans to navigate fairness trade-offs in a manner that makes most sense for their context. Because of this, our package includes not only algorithm and metrics, but also the fairness assessment dashboard--and we hope that the development of UX for fairness assessment / unfairness mitigation will be our key area of contribution.
 
On the unfairness mitigation side, our initial scope is a bit different than AIF360: we are currently only looking at group fairness and have included only three mitigation techniques. However, our techniques are not tied to classification and/or binary sensitive features.

Ultimately we'd love to host at least these types of content:
* UX / visualizations for fairness assessment 
* algorithms for unfairness mitigation
* domain-specific use cases / guides for when to use and when not to use various metrics / algorithms / visualizations etc.

**Comment by firmai** [comment]
I second this! Somehow developers miss this point. 

> domain-specific use cases / guides for when to use and when not to use various metrics / algorithms / visualizations etc.

**Comment by romanlutz** [comment]
I'll close this for now since the question was answered. Feel free to reopen if there is more to discuss.
