### ISSUE TITLE
Proposal: Datasets Module

### ISSUE THREAD

**Issue by koaning** [fairlearn/fairlearn#431]
Just like scikit-learn offers datasets that make it easy for people to play around, it would be nice if this package also offers datasets where fairness is a theme. Over at scikit-fairness we've got a [few of these implemented already](https://scikit-fairness.netlify.app/api/datasets.html) and we could port them over here. 

There's one feature about these `load_`/`fetch_` methods that is worth pointing out; they all raise a `FairnessWarning`. Note that this is a feature, not a bug! It makes people aware that they should not play with this data naively. 

Another benefit of having these datasets around is that it potentially makes writing guides a lot easier as well.

**Comment by romanlutz** [comment]
I'm always a little bit reluctant on that front because those datasets are probably owned by someone, or distributed with some sort of license. If you have experience with these sorts of things I'm happy to learn more :-)

To sort of work around that I've been dumping all such code into a different package called `tempeh` (https://github.com/microsoft/tempeh) which I'm not super eager to maintain because I simply don't have the time to do this properly, but it provides access to all kinds of datasets (among other thigns).

Curious to hear what you think!

**Comment by koaning** [comment]
Sofar I've been able to find enough datasets that (at least I think) do not have ownership issues. Thusfar it seemed fine as long as you properly attribute but this is something that we can check on a dataset by dataset basis. You do probably want to be critical here because you don't want to become a package of datasets. 

In any case; one thing to be aware of is that scikit-learn is dropping support for `load_boston` because of the controversy. I agree that the boston dataset should be removed there, but there are lessons in that dataset in terms of fairness that should not be lost. It may be valid to host here, it will certainly help with education.

**Comment by romanlutz** [comment]
I haven't read up on the details yet, but if there's something to be learned from it I think it would be fabulous to have that illustrated / explained. We've started converting some of the notebooks we currently have into these example notebooks on the webpage https://fairlearn.github.io/auto_examples/notebooks/index.html. The one that's there exists because @adrinjalali put in the effort to get this started. I'll try and do something similar for the other ones we want there.

Do you have a rough idea what this could look like/contain? Any links to read up more on the topic are welcome, of course. Starting to feel like I should open another issue for this specifically :-)

To address the broader question: why isn't there an ML package that provides *all* the datasets?
I know that lots of packages have a few datasets sort of attached to them, but I can't say I like this pattern. Not that that should prevent us from going down that path if it's what everyone else does...

**Comment by koaning** [comment]
You could make a package with *all* the datasets, but it can get rather heavy. You may download 100s of megabytes if you're not careful. 

I guess nothing is stopping me from making a package that contains good datasets for educational purposes. But then you'll have a dependency in your docs. If the package fails, your docs fail. 

To some extend the `kaggle` library does this. But it requires a login, which is super annoying and it forces datasets to be saved in a user folder (they do that to prevent many downloads I imagine).

**Comment by romanlutz** [comment]
I liked the approach of just providing the code to download it from the original location. That means the package is tiny (it's just code), and it can download it on demand. If the data moves elsewhere you lose it, though. And you'd need caching (or keep downloading every time). That may also solve the data licensing issue because the package itself doesn't make data available. So that's kind of what I tried to do with `tempeh` but it's a very raw package...

**Comment by koaning** [comment]
For scikit-fairness we were considering hosting it on github and allowing users to download the raw file that way. Another option would be s3 or google storage.

**Comment by adrinjalali** [comment]
Why not use [openml](https://www.openml.org/)? It has tons of datasets, you can easily add a dataset to it, and sklearn has a `fetch_openml` routine which can even return a pandas dataframe. Is there anything in our datasets which prevents them from being on openml?

**Comment by koaning** [comment]
I never heard of that project before but from clicking around it certainly seems like an option. @adrinjalali are you familiar with the project? It would be nice to have some guarantee that the project will exist for the for-see-able fututre. 

If so, I can start making some `fetch_` methods for [these three datasets](https://scikit-fairness.netlify.app/api/datasets.html). Unless there's other objections.

**Comment by adrinjalali** [comment]
We have been investing quite a bit on the sklearn side to properly support it, and we're we're very much in touch with them as it's been a collaborative project. We have incorporated its usage quite a bit in our examples as well. We casually simply get the data directly w/o having a dedicated `fetch_...` method. So I'd say we're betting on it.

For instance, in [this](https://scikit-learn.org/dev/auto_examples/inspection/plot_permutation_importance.html#sphx-glr-auto-examples-inspection-plot-permutation-importance-py) example you have:

``` python
X, y = fetch_openml("titanic", version=1, as_frame=True, return_X_y=True)
rng = np.random.RandomState(seed=42)
X['random_cat'] = rng.randint(3, size=X.shape[0])
X['random_num'] = rng.randn(X.shape[0])

categorical_columns = ['pclass', 'sex', 'embarked', 'random_cat']
numerical_columns = ['age', 'sibsp', 'parch', 'fare', 'random_num']

X = X[categorical_columns + numerical_columns]
```
I think `fetch_...` methods would make sense as a convenience method if there's some preprocessing you want to apply to the data, for instance separating the sensitive features maybe?

**Comment by koaning** [comment]
If nobody objects, I might start working on a first example for `fetch_boston` then. 

Any comments on the idea for raising `FairnessWarning` while the fetching works?

**Comment by adrinjalali** [comment]
Is be happy with having the `FairnessWarning` if we also tell people how to suppress it. As a user I'd like to not have the warning if I know what I'm doing (and also not have it in the CI)

**Comment by koaning** [comment]
Would this work? 

```
fetch_boston(..., supress=False)
fetch_boston(..., supress=True)
```

**Comment by adrinjalali** [comment]
I'd probably call it `warn`, but yeah that works.

**Comment by kevinrobinson** [comment]
@adrinjalali cool to learn about openml.org, I didn't know about that either! 👍 

Adding datasets seems great, although I'm not following what raising a `FairnessWarning` helps with in this context.  I'm imagining that any people calling methods like `fairlearn.load_boston()` are doing so because they are following examples or notebooks the project has created.  It's not like people are coming to `fairlearn` every day for all their dataset needs :)

If folks want to collaborate on specific example notebooks for datasets, I'd be into that (eg, https://github.com/fairlearn/fairlearn/issues/418, https://github.com/fairlearn/fairlearn/issues/419, https://github.com/fairlearn/fairlearn/issues/413, or https://github.com/koaning/scikit-fairness/issues/31).  I think there's a lot of educational value to be had in that direction, particularly in going beyond the mechanics of calling the algorithm.

**Comment by kevinrobinson** [comment]
fyi in poking around openml.org, the first 'study' listed is FairML by @hildeweerts.  It's recently added and doesn't have anything in it yet, but she might separately be working on datasets or have thoughts.

**Comment by hildeweerts** [comment]
I think leveraging OpenML is a great way for loading data sets - but I am 100% biased as one of my colleagues is the founder of OpenML and I've worked with the team before ;)

I recently came across [this paper](https://arxiv.org/abs/2001.09784) which a.o. lists several data sets that have been used to evaluate fair ml approaches. I've added the ones that are already on OpenML to the study @kevinrobinson mentioned. The statistics on the web interface seem to be broken, which is why it does not look like anything is added yet, but if you go to https://www.openml.org/s/241/data you'll see it contains 5 data sets.

One of the things I might want to work on is a benchmark study on how well different unfairness mitigation approaches work in different scenarios, including both synthetic and 'real' data sets. I've done a benchmarking project using OpenML before (see https://www.openml.org/s/98) and it works quite well for that purpose.

**Comment by kevinrobinson** [comment]
cool!  I'm wary that adding many datasets and running evaluations across them may invite the abstraction traps outlined in [Selbst et al. (2019)](https://andrewselbst.files.wordpress.com/2019/10/selbst-et-al-fairness-and-abstraction-in-sociotechnical-systems.pdf).

If folks do want to go forward in that direction, one minimal step might be to include a description of how the data was collected and labeled, and a potential deployment context.  The framing of 'dataset' abstracts that away, which then makes it very hard to evaluate how well various algorithmic approaches contribute to assessing or mitigating any real-world harms.

**Comment by MiroDudik** [comment]
I think that we should surface the dataset issues explicitly. If we have functions of the form `fetch_<dataset>` then the docstrings can include any issues re. data collection / labeling and the deployment context. Other alternatives:
* a section in the user guide
* maybe there's a suitable place on OpenML?

The matching `FairnessWarning` could include the link as to where to find this information.

**Comment by koaning** [comment]
If people agree that the idea of a datasets module is valid then I can close this issue and start a new issue for datasets that I’d like to add. That way we can debate per dataset. 

For now I’ll explore using the openml service to host ‘fetch_boston’ and I’ll make a seperate issue for it.

**Comment by koaning** [comment]
I've made a work in progress PR so we can discuss implementation there. Will close this issue and split it up so that we can debate per dataset.
