### ISSUE TITLE
Feature Request: fetch_boston

### ISSUE THREAD

**Issue by koaning** [fairlearn/fairlearn#435]
The `load_boston` dataset is moving out of scikit-learn (for good reason) but as an educational example it would be good to host it here and to properly document the issues with it. 

There is a WIP PR for this issue https://github.com/fairlearn/fairlearn/pull/434.

**Comment by riedgar-ms** [comment]
I may have missed another discussion, but @romanlutz created the `tempeh` package, which has been a source of cleaned data. That package is still under the "Microsoft" org, though.

**Comment by romanlutz** [comment]
Just chatted with @riedgar-ms about this and we're very much on board with @koaning 's idea! If there are no license/ownership issues I think that's a great idea. We should probably have some descriptions related to it.

I'm not super opinionated about this and like your PR and suggestions to have datasets in Fairlearn. The only concern is around ownership. Would hate to violate terms of the dataset owner. I tried adding another dataset with the same blueprint you provided, @koaning , and that worked really well. I can add all fairness-related ones we have in `tempeh`, and perhaps that makes the entire package somewhat redundant. In that case I'm happy to get rid of it. It was always meant as a supplemental piece, so that's actually a best case scenario.

**Comment by koaning** [comment]
https://github.com/fairlearn/fairlearn/pull/494

**Comment by romanlutz** [comment]
Closing this and opened #507  as a follow-up to add the corresponding documentation/user guide/notebook (whichever is appropriate).
