### ISSUE TITLE
Separate functions for different aggregations of the same fairness metric?

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#457]
I was wondering whether there is a particular rationale for having separate functions for different types of aggregation of the same fairness metric, e.g. demographic_parity_difference and demographic_parity_ratio.

From a user perspective, I would expect "demographic_parity" to be a single function and the way it aggregated (ratio/difference/etc.) a function argument. Especially if we would like to include some more information in the documentation on the rationale behind different metrics, the current API would require us to copy this multiple times.

**Comment by riedgar-ms** [comment]
Tagging @MiroDudik who added that part of the metrics API.

**Comment by romanlutz** [comment]
Linked @MiroDudik 's proposal https://github.com/fairlearn/fairlearn-proposals/pull/9/files which sheds light on these things.

Although after re-reading this it seems like there's two ways to get at this:
```
demographic_parity_difference(...)
difference_from_summary(selection_rate_group_summary(....))
```
and there's various things one can extract from the summary (difference, ratio, min, max).

Super useful to hear about your expectations in terms of API. Let's wait for @MiroDudik as well in case I missed something.

**Comment by hildeweerts** [comment]
I did not see this pull request yet - thanks for linking! I don't think it contains arguments on *why* this particular API design is proposed, does it? I might have missed that though. Perhaps we can discuss API design during the developer call this Thursday? It might be a better medium for this type of discussion.

**Comment by MiroDudik** [comment]
Agreed let's chat on the call. I see an agenda emerging :-)...

But at least some quick arguments that we went through. Parity is a constraint (or a set of constraints), so the metrics should not be called "parity". One idea would be to call the metric "disparity", so we'd have `demographic_disparity(..., metric='difference')` or something like that. This might be okay, but it becomes verbose when generalizing to things like true positive rate, when we'd end up with `true_positive_rate_disparity(..., metric='ratio')` and we'd probably have a default `metric='difference'`. So we opted for `true_positive_rate_difference` and `true_positive_rate_ratio` instead--it makes clearer what you're measuring (rather than rely on the default) and is less verbose.

**Comment by romanlutz** [comment]
Related conversation going on at https://github.com/fairlearn/fairlearn-proposals/issues/12

**Comment by riedgar-ms** [comment]
@hildeweerts do we need this any more? I think that the `MetricFrame` addresses this?

**Comment by hildeweerts** [comment]
Yes! We can close this issue
