### ISSUE TITLE
`constraint` is not documented in the `ThresholdOptimizer`

### ISSUE THREAD

**Issue by MBrouns** [fairlearn/fairlearn#468]
The docstring parameter seems to be missing here: https://fairlearn.github.io/api_reference/fairlearn.postprocessing.html#fairlearn.postprocessing.ThresholdOptimizer

**Comment by romanlutz** [comment]
@MiroDudik is doing extensive refactoring on this right now #381 . That PR addresses this documentation gap. There's still another gap, of course, and that's the missing user guide. I'll get to that soon, since I'm writing all user guides right now. If you take a look at that PR, feel free to add your review and please mention if there are other shortcomings you notice!

**Comment by romanlutz** [comment]
Closing this since #381 was merged with documentation for `constraints`. Please reopen if there are further issues. Thanks!
