### ISSUE TITLE
How to proceed with PR Gate that runs notebooks against the last released Fairlearn version?

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#472]
This keeps causing confusion, e.g. most recently https://github.com/fairlearn/fairlearn/pull/434#issuecomment-640945245

Any suggestions for how to rename the pipeline? This is complex because in general it should be green/passing. If we make the conscious decision to break something compared to the last version it gets red. From that point onward it stays red until the next release. So we definitely do want to be alerted when it goes red for the first time. That's what makes this tricky. 

@adrinjalali suggested in the past that things like this could perhaps be fixed just before a release. [I hope I'm not rephrasing his ideas in a way that misrepresent them...]

So I'm curious how people feel about this. In a way I feel like solving the documentation versioning in the way scikit-learn does it, i.e. the webpage can be viewed based on whatever version of the package you're using incl. notebook, and therefore you will have no trouble finding the compatible notebook. That would perhaps address the issue sufficiently.

FYI @kevinrobinson helped out some folks over the past week or so who raised this issue here on GitHub, so perhaps you also have thoughts.

FYI @koaning who faced this issue as well.

FYI @riedgar-ms @MiroDudik

**Comment by riedgar-ms** [comment]
I'd say that there's no value to a build which is perpetually red, and hence ignored. Fundamentally, we need to get better about compatibility (which is what my PR over in `fairlearn-proposals` is about). Of course, the build is currently checking _forwards_ compatibility, which is necessarily going to break as features are added (although I believe that the current issues are simply due to naming instability). To keep this build green through such changes, we would need to have tests and notebooks declare their 'minimum supported version.'

Having the documentation versioned is related, and very good to have, but doesn't solve the issue that we have too many breaking changes too often.

Until we get to that v0.5.0 compatibility commitment, it might be worth putting '[Optional]' or something like that on the build name. That will at least reduce the confusion.

**Comment by adrinjalali** [comment]
I don't mean putting anything more than what we already have in master @riedgar-ms . When reviewing a PR, if the PR has to change anything in the tests or the docs to make the CI pass, that means it's probably not backward compatible, and that's enough, isn't it?

**Comment by riedgar-ms** [comment]
@adrinjalali Agreed. But I do like to have builds which double check things :-)

**Comment by adrinjalali** [comment]
What I'm trying to say is that it's the wrong check. Certain changes to master break things and that's okay as far as we document it and/or warn the user. master's not supposed to pass all the tests with an outdated (aka released) version.

**Comment by riedgar-ms** [comment]
If we are trying to provide some level of backwards compatibility, sure `master` should be able to run older tests (within the compatibility window)?

**Comment by romanlutz** [comment]
@riedgar-ms I am not even sure that makes sense. There are tests that use things which aren’t around anymore. For example, the current pipeline is failing because a member name was changed from _<name> to <name>_. That isn’t really a breaking change in some ways because it was underscored to begin with. 
What you’re proposing is in essence a different version (different in scope of tests) of the existing pipeline, right? Perhaps I’m missing something.

I certainly see the point in being intentional about documenting breaking changes better for users. In part @kevinrobinson ’s PR will help with that since we get a dedicated place to document how to upgrade from version to version.

That along with versioned docs should go a long way. I’m not opposed to further checks in principle, but they may be better off not being PR checks.

**Comment by riedgar-ms** [comment]
I know that there will be breaking changes in future, but if we keep having breaking changes for every single release on PyPI, we are neither going to get nor keep users. At some point, we're going to have to start making the promise that code that works with `x.y.z` will also work with `x.y.z+1`. Running the tests of an older version (but *within the compatibility window*) against `master` is a way of verifying that compatibility.

**Comment by adrinjalali** [comment]
> If we are trying to provide some level of backwards compatibility, sure `master` should be able to run older tests (within the compatibility window)?

Imagine we find a bug in a method and fix it, which also changes the output of the method and hence the need to change the tests. Then as a result of your `FIX` your `main`/`master` branch is not backward compatible. This happens quite frequently in my experience and this alone is enough for me not to require full backward compatibility of the `main` branch with the latest release. And if such a fix goes to the `x.y.z+1` release, then those relevant tests are not gonna pass on `x.y.z` and that's intentional and okay.

We also should start using the `.. versionadded` and `.. versionchanged` directives in the docs to help users figure out when/what has changed.

**Comment by MiroDudik** [comment]
I essentially agree with all points raised by @adrinjalali . I really think we should drop this specific test.

On a very basic level -- I am not sure what's the action associated with not passing the test? When I create a PR or review a PR, I already know whether the API is being changed (the current tests are being updated etc.), so anything related to the changes in API should really be caught then.

The issue of how we deal with backward compatibility is a separate one that we should figure on https://github.com/fairlearn/fairlearn-proposals/pull/11 .

**Comment by riedgar-ms** [comment]
> And if such a fix goes to the x.y.z+1 release, then those relevant tests are not gonna pass on x.y.z and that's intentional and okay.

But if we regard `x.y.z` as "supported" then wouldn't a bug fix get backported as a `post[n]` release (although I'm not sure how PyPI handles those if one just specifies `x.y.z` as the version)?

I suppose as @MiroDudik says, it depends on what we want to call 'supported' and what we want our versions to mean.

**Comment by adrinjalali** [comment]
`post[n]` releases are not used as a bug fix release AFAIK ([PEP440](https://www.python.org/dev/peps/pep-0440/#post-releases)):

> Some projects use post-releases to address minor errors in a final release that do not affect the distributed software (for example, correcting an error in the release notes).

A bug fix release should change the version of the software as I understand.

**Comment by riedgar-ms** [comment]
I see - thanks for highlighting that part of PEP440, which specifically says not to put bugfixes into post releases. I'd been thinking about the [SemVer](https://semver.org/) approach, there the `.z` is explicitly supposed to be backwards compatible. So we've been talking at cross purposes.

However, we should follow the PEP440 way.

I then don't see any easy way to monitor API changes, to make sure that we do have backwards compatibility of the API (short of a lot of 'API only' tests). I know that in theory we know from looking at PRs and the Changes.md, but that's manual, not automatic.

**Comment by riedgar-ms** [comment]
However, I think we're getting a bit off-topic. I think that:

- Further backwards-compatibility discussion needs to go over to my larger proposal in `fairlearn-proposals`
- We should have versioned docs
- The current test-notebooks-against-last-release CI build isn't particularly useful, since it's perpetually red
