### ISSUE TITLE
How should the probabilities generated by best_classifier be turned in predictions?

### ISSUE THREAD

**Issue by MatthijsdeJ** [fairlearn/fairlearn#5]
The returned best_classifier gives the probability of a sample belonging to class 1. However, I am conflicted in how I should turn this probability into a prediction.

Intuitively, it would make sense to binarize this probability at a 0.5 threshold. Not doing this would result in [probability matching](https://en.wikipedia.org/wiki/Probability_matching), which would result in suboptimal accuracy.

However, in practice, I find that simply sampling from the probability (predicting class 0 if a random number in [0,1] exceeds the probability) results in better fairness. 

I am wondering what the correct method is.

**Comment by PranavPillai** [comment]
@MatthijsdeJ does the best classifier return probabilities? I'm struggling to get the probabilities; right now, I can only get it to return binary predictions.

**Comment by MiroDudik** [comment]
The `result.best_classifier` is in general a **randomized** classifier. When it returns a number between 0 and 1, it should be interpreted as the probability with which the decision maker should assign class 1, so the sampling that @MatthijsdeJ describes is the correct thing to do.

The number that it returns should **not be interpreted** as the probability that the example belongs to class 1. That's why thresholding at 0.5 is not justified. The actual reason for randomization is to enable the full range of accuracy / fairness tradeoffs. Randomization can also help mitigate unfairness without affecting accuracy: for example by randomizing between two classifiers that have the same accuracy, but differ in which of the subpopulation they put at an advantage it is possible to improve fairness without affecting accuracy.

In practice, it can be desirable to use deterministic classifiers. In that case, you can look at  `result.classifiers` to check whether any of them works. These are the classifiers that are used to compose the output of `best_classifier` according to weights in `result.weights`.

**Comment by romanlutz** [comment]
I've marked this as a feature request to add a classifier to the result that automatically provides the binary output by randomly taking the result of one of the selected classifiers based on their weights.

We'll likely get to this within the next few weeks.

**Comment by romanlutz** [comment]
Our `predict` method in `ExponentiatedGradient` should be doing this now. @MiroDudik can you sanity check that I'm not confusing myself?

**Comment by romanlutz** [comment]
A lot of this code has changed since the issue was created. I think #65 tackles the remaining problem more holistically by asking to provide explanations for what to expect from the prediction-related methods.
