### ISSUE TITLE
Documentation for fetch_boston

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#507]
This is a follow-up to #435 and #494 to add documentation for `fetch_boston`. We need to find a good way to highlight the issues with this dataset as an educational example. Depending on the chosen way this may end up as a user guide or notebook (whatever is more appropriate).

There are plenty of resources to base this on, e.g. https://github.com/fairlearn/fairlearn/pull/434#discussion_r437683926 (comment from the original PR).

A great first step would be to compile a list of related sources and to post them in this thread. After that we can summarize the info and decide how to add it to the docs.

**Comment by alliesaizan** [comment]
Hi @romanlutz, I'd like to start looking at this! I will review the previous issues but please let me know if you have additional information that can provide context.

**Comment by romanlutz** [comment]
Awesome!!! This is such an important one, I'm glad you are interested in starting 🙂

In think the comment linked in the issue description is where I'd start. Even just creating a list of sources would be a great step. Feel free to update this issue with comments on your progress, e.g., "here's what I found so far".

We'll likely want a new user guide section on this dataset, but we can discuss specifics when you have something you'd like to add. In terms of objective I'm really thinking of educating readers about the origins of the dataset and why using it is problematic.

 @koaning has a lot of thoughts on this topic, too, so perhaps there's something he'd like to add (?)

**Comment by koaning** [comment]
I suppose I could add a guide that's pretty much the content of this video; [https://youtu.be/Z8MEFI7ZJlA?t=769]. 

It's the material that we could almost pretty much copy from [the scikit-lego fairness tooling](https://scikit-lego.netlify.app/fairness.html). That way we'd also have a guide for the CorrelationRemover component. 

I other folks prefer to pick this up: be my guest.

**Comment by alliesaizan** [comment]
Hi @romanlutz, I went through all the issues cited (though did not do a deep dive into the research papers linked). @koanig has linked a few resources, here and elsewhere, that provide good starting places!

List of resources:
- The original [paper](https://deepblue.lib.umich.edu/bitstream/handle/2027.42/22636/0000186.pdf?sequence=1&isAllowed=y) that introduced the boston housting dataset
- [Issue 466](https://github.com/fairlearn/fairlearn/issues/466) discusses porting `Demographic Parity Classifier` and `Equal Opportunity` from scikit-fairness to fairlearn, and Kevin suggests using the Boston housing dataset as an example
- Boston housing dataset used for fairness walkthrough: https://scikit-lego.netlify.app/fairness.html, same as https://scikit-fairness.netlify.app/fairness_boston_housing.html. I think this guide is pretty thorough, though
- [Benchmark notebook using boston dataset](https://gist.github.com/koaning/1a606e07c9b27d1889ada4185959d87a) from [issue 430](https://github.com/fairlearn/fairlearn/issues/430#issuecomment-632690069) that tests out `InformationFilter` and `CorrelationRemover`. Findings: (1) the hyperparameter alpha should not be constrained to (0,1) and (2) that two functions should be moved to fairlearn from scikit-fairness, `GramSmidthFilter` (aka `InformationFilter`?) and `CorrelationRemover`. 
- A [discussion in scikit-learn](https://github.com/scikit-learn/scikit-learn/issues/16155) about how one of the columns in the boston dataset encodes systemic racism, and the subsequent `FairnessWarning` now included in the dataset load. I don't know if the problematic column `B` is still in the dataset as implemented in fairlearn or if it was removed?
- In [issue 31 of scikit-fairness](https://github.com/koaning/scikit-fairness/issues/31), the user who raised most of the fetch_boston comments suggests taking a sociotechnical approach to the user guide by explaining how a team of diverse participants, some technical and some not, might be able to offer different perspectives on the dataset. Is that an approach we would want to take in the documentation? So not just highlighting the technical issues that other users have cited before in other comments and other repositories, but maybe a way of using fairlearn to address all the additional feedback different stakeholders might have about the data. 
- The purpose of the boston dataset was originally to measure air quality! I definitely think we should address that, given how differently it's used now.
-[Issue 435](https://github.com/fairlearn/fairlearn/issues/435) discusses scikit-learn phasing out the boston dataset, but given that this issue is a year old it may be overcome by events.

I am curious as to whether you have any ideas about what we might want to touch upon that goes beyond koanig's [tutorial](https://scikit-fairness.netlify.app/fairness_boston_housing.html). Maybe we could adapt that analysis for fairlearn and add some of the in- and post-processing functionalities to test outcomes? 

Overall, I am thinking the user guide post could have a structure as follows:
1. Introduction to the boston housing dataset - where does it come from, where is it currently used, where is it deprecated
2. Issues with the dataset - display via summary statistics and a 'typical' prediction pipeline. Here we can also talk in depth about scikit-learn issue #16155.
3. Run through the diagnostic analysis in the scikit-fairness blog post, adjusting for changes in fairlearn syntax
4. Discussion about what we found, how well different processing methods work at achieving some fairness goal, and general recommendations about using the dataset

Please let me know what you think!

**Comment by romanlutz** [comment]
Thanks @alliesaizan for the summary!!!

Some thoughts:
- `CorrelationRemover` is already part of Fairlearn thanks to @koaning https://fairlearn.org/main/api_reference/fairlearn.preprocessing.html#fairlearn.preprocessing.CorrelationRemover
- We never did anything to the dataset so it should be in the original configuration. In fact, you can try calling `fetch_boston` and the `feature_names` should include the `B` column. For me it shows `['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']`. I think the main reason for including it in Fairlearn is to show this bad example.
- Writing about the origin of the dataset and then considering how it's been used since is absolutely important. I would say that already captures some of the issues. One can be arbitrarily ambitious with this, but I've found it to be beneficial to start small and iterate on that. Kevin outlined a pretty ambitious agenda that would be awesome to get to IMO, but it also requires a lot of time from several people. This documentation might provide the foundation for this to happen eventually.
- I like your outline. I'm not 100% sure about using the mitigation techniques because I really feel like putting the dataset first. On the other hand, I don't quite know what you have in mind there (as in "what are you trying to show using the mitigation techniques?") so I'm definitely open to looking into it. The first three points you made are definitely 100% in line with what I thought of.

I'd also love to hear if others have thoughts, for example @hildeweerts @LeJit @MiroDudik

**Comment by alliesaizan** [comment]
@romanlutz thanks! I agree about putting the dataset first, and can hold off on the mitigation techniques for now. I think my intention with thinking about mitigation techniques is to show readers how to address disparities if they're using a similar type of dataset, but I don't want to give the impression that data processing is a panacea for all the issues with the boston data. Given that we for sure want to address the first three bullets, I can start working on sketching those sections out!

**Comment by hildeweerts** [comment]
I agree with everything @romanlutz mentioned and I am looking forward to read your drafts @alliesaizan!

**Comment by alliesaizan** [comment]
Hi @romanlutz and @hildeweerts, [here](https://github.com/alliesaizan/fairlearn-volunteering-files/blob/main/Revisiting%20the%20Boston%20Housing%20Dataset.ipynb) is my first draft of the Boston housing article. I used the same method as @koaning to turn the problem into a classification problem so we could show the typical fairlearn evaluation metrics. I am open to any and all feedback! Please also let me know if/how you'd like to expand the article.

**Comment by romanlutz** [comment]
There's a lot I like about this and huge kudos for creating this summary. Personally, I struggle with commenting on Jupyter notebooks because there's no way to use a "comment on line xyz" functionality. We could either add it as a user guide section (which is what I was thinking) OR an example notebook. In either case you\d need to create a PR against the Fairlearn repo so that we can provide feedback by line.

@hildeweerts @mmadaio how do you feel about user guide vs. example notebook? I'm leaning user guide.

### If it's a user guide section
Copy the content into a restructured text (`.rst`) file? I'm thinking a new file under `docs/user_guide`, perhaps `datasets.rst`. That would need to be listed in the corresponding `index.rst`. This is the first such dataset investigation (of hopefully many!) so we can create subsections/-pages there eventually but you can just use `datasets.rst` to start with. Restructured text is formatted differently, but I wouldn't worry too much about it for now. I think we're just looking high-level and then progressing to details (structure, goals, then content, eventually phrasing, formatting). 

## If it's an example notebook

To have it render in our "examples" section you'd need to convert it to a `.py` file. A tool like [jupytext](https://jupytext.readthedocs.io/en/latest/using-cli.html) should do the trick. Then just drop it into `examples and make sure the file name starts with `plot_`

### Advice that applies in both cases

Then you can build the docs using instructions from https://fairlearn.org/main/contributor_guide/contributing_documentation.html

If you need infos on how to create a fork and subsequently a PR: https://github.com/romanlutz/fairlearn-scipy-sprint

I'm sure @hildeweerts and @mmadaio, perhaps also @michaelamoako and @brkifle, would like to chime in once that PR exists.

**Comment by alliesaizan** [comment]
@romanlutz I was also thinking this would go in the user guide, so I can proceed with setting up the rst file!

**Comment by koaning** [comment]
![image](https://user-images.githubusercontent.com/1019791/135070378-16c13357-2d05-4294-a539-c27c53d2c852.png)

The table seems to have two columns missing: B and LSTAT.

**Comment by alliesaizan** [comment]
Hm @koaning I think that is an issue with the formatting; I did not take the columns out intentionally. See how a bunch of columns got caught up in the Description for TAX? I will work on adjusting the rst formatting so those columns do not get squished together.

**Comment by alliesaizan** [comment]
Suggest closing this due to PR #1000, which added the documentation to _main_.

**Comment by hildeweerts** [comment]
Thank you for flagging this @alliesaizan, I will close the issue!
