### ISSUE TITLE
Datasets in Fairlearn?

### ISSUE THREAD

**Issue by anirbandasgupta** [fairlearn/fairlearn#530]
I am having trouble with the following when I tried it out in Colab.

```
!pip install fairlearn
from fairlearn.datasets import fetch_adult
```

It does not seem to find datasets module and throws up the following error.

```
      1 get_ipython().system('pip3 install fairlearn')
----> 2 from fairlearn.datasets import fetch_adult
      3 
ModuleNotFoundError: No module named 'fairlearn.datasets'
```

Same issue when I tried using conda in my system. Any help is appreciated.

**Comment by riedgar-ms** [comment]
The version of Fairlearn currently available through PyPI does not have the `datasets` module. In order to use the `datasets` module, you will need to clone the Fairlearn repo, and `pip install` the cloned directory. If you do that, please make sure that you use examples from the clone - we have had a number of breaking API changes since the v0.4.6 release.

**Comment by romanlutz** [comment]
We should actually fix that quickstart to not use the datasets module before releasing the next version. My bad!

**Comment by anirbandasgupta** [comment]
Thanks, the older version worked.

**Comment by riedgar-ms** [comment]
Sorry about this - we know we need to get better about breaking changes, and we are planning to provide versioned documentation to help with unavoidable breakages.
