### ISSUE TITLE
"GroupLossMoment" versus "BoundedGroupLoss"

### ISSUE THREAD

**Issue by nina-hua** [fairlearn/fairlearn#556]
Hello, I've installed fairlearn using pip and in the init script, "GroupLossMoment" is present while "BoundedGroupLoss" isn't. Comparing this script to the one found in the Github, they're not consistent, which I'm assuming is because I've installed fairlearn with pip instead of pulling from the repo. Does  "GroupLossMoment" work comparably to "BoundedGroupLoss"?

**Comment by romanlutz** [comment]
Hi @nina-hua ! Your assessment sounds correct :-)
`GroupLossMoment` has been renamed to `BoundedGroupLoss`, but it's also a little bit more general now. GLM is only usable with `GridSearch`, while BGL is usable with `GridSearch` and `ExponentiatedGradient`. [When using BGL with `ExponentiatedGradient` you need to provide the `upper_bound` argument.] Otherwise they should behave the same way.

Please let me know if there are other questions! We definitely need to write a set of changes from v0.4.6 to v-next and publish them on the webpage (besides CHANGES.md). Since it's also related: the multi-version support on the webpage that @riedgar-ms  is working on will be very useful.

**Comment by nina-hua** [comment]
Thanks Roman! Do you have a link to older documentation on how to use GroupLossMoment?

**Comment by romanlutz** [comment]
I don't unfortunately, but you can use it just like `BoundedGroupLoss` except that there's no `upper_bound` argument: https://fairlearn.github.io/user_guide/mitigation.html#bounded-group-loss

It will only work with `GridSearch`, though.

**Comment by nina-hua** [comment]
Thanks Roman! I'm actually trying out GridSearch with the Boston Housing Dataset. But I'm running into an error setting the grid size. I've tried using 10 versus 1000 estimators, but I'm not sure how to mitigate this issue?
`Message:'Generating a grid with {} grid points. It is recommended to use at least {} grid points. Please consider increasing grid_size.'
Arguments: (10, 31828687130226345097944463881396533766429193651030253916189694521162207808802136034115584)`

**Comment by nina-hua** [comment]
Is there a tutorial on how to use GridSearch with regression problems since I've only stumbled upon classification problems?

**Comment by romanlutz** [comment]
We don't have one yet. Wow that's a big number. How many groups do you have in that example? The recommended grid size is exponential in the number of groups.

I also want to point out the fairness issues with the Boston housing dataset. More context is available at this link: https://github.com/koaning/scikit-fairness/issues/31

**Comment by nina-hua** [comment]
By groups, do you mean the sample size? I did an 80/20 train/test split with the Boston dataset, so my training data set comes out to be 404 samples.

Yup, definitely chose this dataset on purpose because I was assigning the "B" feature as a sensitive feature to explore.

**Comment by romanlutz** [comment]
That's likely the problem. By default it treats the sensitive feature data as individual categories and you probably have roughly 400 different ones. I don't have enough context on this particular dataset to make any recommendations, but I'd suggest thinking about the application context first. What do you envision to do with such a model?

FYI @kevinrobinson and @koaning who have worked with this dataset before.

In general, when the sensitive feature is continuous (e.g. age) binning is the way to go.

**Comment by koaning** [comment]
Binning ... or use a technique like an InformationFilter as demonstrated [here](https://scikit-lego.readthedocs.io/en/latest/fairness.html#How-it-Works).

**Comment by nina-hua** [comment]
Thanks for the help Roman and Vincent! I wanted to build a model to predict the median house price with a dataset that's known to be biased to demonstrate how Fairlearn & InterpretML can be used in future projects at work. I'll try out the binning method for now.

**Comment by kevinrobinson** [comment]
@nina-hua hello!  If you're trying to make the case at work for using these assessment and mitigation approaches, it can really help to frame the impact in terms of how it reduces real harms to real people.

If you're into research papers, [Language (Technology) is Power: A Critical Survey of “Bias” in NLP (Blodget et al. 2020)](https://www.aclweb.org/anthology/2020.acl-main.485.pdf) suggest some ways to approach fairness work that can lead to more productive conversations than focusing on bias alone. 

More practically, in my experience the aggregation in the Boston housing dataset means it's particularly challenging to use as a kind of proof of concept for this kind of fairness work.  You really need a task that's embedded in some social system to talk about harms, and to translate the impact of fairness metrics to accessible human terms so that various stakeholders can see why the work matters and is worth doing.

I'd be happy to collaborate or chat more about scenarios or datasets that might be more directly relevant for your work, or that might help you with kicking off those conversation on your team.  Feel free to chat here or ping in https://gitter.im/fairlearn/community if you'd like!

**Comment by nina-hua** [comment]
Thanks! I'll discuss this with my manager and will take you up on that!

**Comment by nina-hua** [comment]
This is an aside, but would there be any capability of having Fairlearn be compatible with glassbox models from InterpretML? I thought about how Fairlearn's GridSearch could be used to improve an ExplainableBoostingRegressor from InterpretML but because ExplainableBoostingRegressor does not contain a "sample_weight" argument, I'm receiving this issue. 

![fairlearn_error](https://user-images.githubusercontent.com/40807472/90420505-e7e73300-e06c-11ea-997b-4e8acfb2df6f.png)

**Comment by romanlutz** [comment]
We require `sample_weight` at this point and EBM doesn't have that currently https://github.com/interpretml/interpret/blob/67da4f4913e01340324f07ea95074784db6c337d/python/interpret-core/interpret/glassbox/ebm/ebm.py

This is already tracked through #4 . Nobody is currently working on this feature, though.  @mesameki FYI

If you really want to use it you could perhaps write a wrapper for your regressor that has `sample_weight` in the `fit` method and handles the reweighting. I definitely recommend filing a feature request with `interpret` to ask for the `sample_weight` in the meanwhile since I can't give any ETA for this feature. I've marked it as "help-wanted" in the meanwhile so that contributors know that they can pick it up.

**Comment by anindya5** [comment]
Will the BoundedGroupLoss be available in pip or conda anytime soon?

**Comment by romanlutz** [comment]
@anindya5 yes! With the next release it'll be available. @riedgar-ms I think the metrics updates & doc updates are the main blockers for v0.5.0, is that correct? If so, do you have a (rough) ETA?

**Comment by romanlutz** [comment]
anindya5 I was discussing this with @riedgar-ms yesterday. My best guess would be end of October but early November is possible. Do the workaround with v0.4.6 to use GroupLossMoment or alternatively installing the development version from the master branch not work for you?

**Comment by anindya5** [comment]
@romanlutz , every time I am trying to clone the repository for advanced install, I am getting permission denied. Not sure why is that

**Comment by romanlutz** [comment]
Can you post the command & error? git clone should do it.

**Comment by anindya5** [comment]
@romanlutz  - i was able to fork and clone, will try the boundedgrouploss now

**Comment by romanlutz** [comment]
#613 will provide a place on the website to answer these sorts of questions ahead of a release, and #551 provided the versioned docs, so we should be set up to avoid confusion like this in the future :-)
