### ISSUE TITLE
Interactive dashboard doesn't show on Azure Compute Instances, either JupyterLab or Jupyter Notebooks

### ISSUE THREAD

**Issue by maurominella** [fairlearn/fairlearn#558]
If I setup a local Conda environment and run FairLearn dashboards, it works:

![image](https://user-images.githubusercontent.com/32428960/90260627-0f12ea00-de4c-11ea-9c2d-bbd1f1bd35ed.png)

If I run the same notebook -and libraries- on an Azure Compute Instance, it doesn't. More specifically:

- On JupyterLab, it reports "Error displaying widget: model not found"

![image](https://user-images.githubusercontent.com/32428960/90260504-df63e200-de4b-11ea-82d2-6b4bd0bf5946.png)

- On a Jupyter Notebook (running on Azure Compute Instance), the dashboard shows up but when I try using it, it gets stuck on this window:

![image](https://user-images.githubusercontent.com/32428960/90259875-066de400-de4b-11ea-8962-899c3a73ad48.png)

I checked the pip libraries, I simply have much more on Azure than locally but the common ones are the same (latest) version, installed today.
I also read that JupyterLab is still non supported, but I supposed that Jupyter Notebooks are supported, even on Azure, aren't they?

Thanks

**Comment by romanlutz** [comment]
@maurominella you're right in that JupyterLab isn't support yet. It should work in Jupyter on Azure. You wrote "Azure Compute Instance" so I assume it's an [AzureML Compute Instance](https://docs.microsoft.com/en-us/azure/machine-learning/concept-compute-instance). The dashboard itself is showing up, just the calculation seems to not finish.

Sometimes it does take a little time to calculate if the dataset size is really large. I understand from your description that that can't be the case since it worked locally with the same data, right? Please confirm the size of the data (# of rows).

Something that jumped out at me from your code is that you're passing the `sensitive_feature_names` as an `np.array` as opposed to a list of strings. It doesn't make a difference when I'm running in v0.4.6, though.

Finally, I can't tell from your code what type `ys_pred` is. It should be a dictionary like `{"unmitigated": unmitigated_predictor.predict(X_test)}`, but I can't be sure from the partial snippet. If you can reproduce the same issue with a minimal example that would be very helpful.

**Comment by maurominella** [comment]
Hi @romanlutz , thanks for your answer. I can't say why, but it works now. I just rebooted the VM.

I confirm it's this AzureML Compute Instance:
![image](https://user-images.githubusercontent.com/32428960/90600276-8c48b100-e1f6-11ea-8f7b-6162e0f84d64.png), even after reboot.

ys_pred is a dict whose first element is the model_id and the second one is the array with the predictions as described at [this link](url)

```
{'mauromi_model_classifier_LR:7': array([0, 0, 0, ..., 0, 0, 1]),
 'mauromi_model_classifier_SVM:6': array([0, 0, 0, ..., 0, 0, 1]),
 'mauromi_model_classifier_CBC:6': array([0., 0., 0., ..., 0., 0., 0.])}

```

Anyway, problem solved. Thanks again, Mauro
