### ISSUE TITLE
Consider changing logo link in the documentation page from contents to index

### ISSUE THREAD

**Issue by leonarduschen** [fairlearn/fairlearn#570]
#### Describe the issue linked to the documentation

Clicking the logo leads to contents instead of index. This is because `pydata-sphinx-theme` sets logo href to `master_doc` (which in `fairlearn` case is contents).

#### Suggest a potential alternative/fix
I'm not sure if linking the logo to `index` instead of `content` is really what `fairlearn` wants, but an extra opinion from `fairlearn` maintainers would be awesome.

I have created an issue in `pydata-sphinx-theme` and will mention this issue over there (https://github.com/pandas-dev/pydata-sphinx-theme/issues/245)

**Comment by romanlutz** [comment]
This is mostly self-inflicted since we wanted to have a custom title page, so the docs "root" is `contents` as you're describing, and not index. I don't consider it to be a big issue to be honest. Adding a link from contents back to the `index` page may be a useful "band aid" solution until there's perhaps a solution from pydata-sphinx-theme. Feel free to open a PR!
