### ISSUE TITLE
Can't use sklearn.Pipeline with GridSearch.

### ISSUE THREAD

**Issue by Dref360** [fairlearn/fairlearn#580]
Hello,

I may be wrong, but GridSearch does not allow [sklearn.Pipeline](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html) for its estimator.
This would be a useful feature have!

## How to reproduce.
In `test/unit/reductions/grid_search/test_grid_search_arguments.py` add:

```python
# Additional Imports
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Set up Pipeline estimator
class TestPipelineEstimator(ConditionalOpportunityTests):
    def setup_method(self, method):
        self.estimator = Pipeline([('scaler', StandardScaler()), ('logistic', LogisticRegression(solver='liblinear'))])
        self.disparity_criterion = DemographicParity()
```

Then : `pytest test/unit/reductions/grid_search/test_grid_search_arguments.py` would fail with:

```
ValueError: Pipeline.fit does not accept the sample_weight parameter. You can pass parameters to specific steps of your pipeline using the stepname__parameter format, e.g. `Pipeline.fit(X, y, logisticregression__sample_weight=sample_weight)`.
```

### Proposed solution

In GridSearch constructor, we could allow specifying the key for `sample_weight`.

Ex. `GridSearch(self.estimator, self.disparity_criterion, grid_size=2, sample_weight_key='logistic__sample_weight')`

I already made the test so I can add the solution too if it is approved.

**Comment by romanlutz** [comment]
@Dref360 this is a great discovery! I suspect we'll find the same issue with `ExponentiatedGradient` since it also relies on passing `sample_weight` to the estimator. What I don't quite understand in your example is how the pipeline knows that it's for that step since the step is named `logistic` but you prefix the key with `logisticregression`. Is that perhaps an issue with the example?

I like your proposed solution! @MiroDudik do you have thoughts (since this would be an API change/extension)?

What this really makes me think about is whether we are looking at this a bit backwards. @adrinjalali may have thoughts on this. If we use a pipeline like the one in your example, shouldn't the mitigation technique be applied after the scaling, i.e. shouldn't the mitigation technique be a part of the pipeline?

**Comment by adrinjalali** [comment]
The mitigation should definitely be a part of the pipeline to avoid data leackage. Otherwise your mitigation technique is going to see the whole dataset which it shouldn't.

**Comment by riedgar-ms** [comment]
It would seem odd that our Estimators would have a capability (overriding an argument name) when the `sklearn` estimators do not.  What we might want is the ability to override the `sample_weight` name when calling the underlying Estimator, in case something that we're wrapping uses another name.

**Comment by Dref360** [comment]
>  Is that perhaps an issue with the example?

Yes, sklearn does not know the name of the step, it just show `logisticregression__sample_weight`. In reality, it should be `logistic__sample_weight` (from the name I put in the Pipeline arguments).

**Comment by riedgar-ms** [comment]
An update on my earlier comment, now that I've woken up a bit more. If I understand @adrinjalali  correctly, when trying to use Fairlearn in a pipeline, the Fairlearn estimator should go into the pipeline itself. The line to construct the pipeline should look something like:
```python
self.estimator = Pipeline([('scaler', StandardScaler()), ('estimator', GridSearch(LogisticRegression(solver='liblinear'), constraint=DemographicParity()))]
```
which definitely makes sense, and should work as-is (we should check this, though). It feels odd to have some external algorithm (such as `GridSearch`) 'reach in' to just one part of the Pipeline.

However, we could consider having the argument name override capability, to allow ourselves a little more flexibility in supported estimators, if we found some common package which (for example) used `sample_weights` instead of `sample_weight`.  We might prefer just to tell users to write a wrapper for such cases, though.

**Comment by adrinjalali** [comment]
More like, do the `GridSearch` on the `pipeline`, would that not work?

**Comment by romanlutz** [comment]
> do the `GridSearch` on the `pipeline`
Isn't that the original example @Dref360 is showing? That seems to be in contrast with your earlier comment @adrinjalali . Perhaps I'm misunderstanding.

What Richard drew up is basically what I meant originally, although I don't know if that's preferable to having `GridSearch` wrap the pipeline. A quick search showed one `sklearn` example with `GridSearchCV` wrapping `Pipeline`, but I can't tell whether that's a pattern to copy.

**Comment by adrinjalali** [comment]
To me, `GridSearch` is not a _mitigation technique_, it's rather finding a set of hyper parameters which satisfy a set of constraints. Ideally `sklearn`'s API gives you all you need so that you could remove `GridSearch` from `fairlearn` and just use `GridSearchCV`, in which case you'd put the whole pipeline in it. On the other hand, I would put `InterpolatedThresholder` inside a pipeline instead of passing the pipeline to it. Am I missing something?

**Comment by romanlutz** [comment]
@adrinjalali I agree that that's how it should be, but right now it isn't. There's one potential problem that (at least in my mind) is keeping us from doing it this way. `GridSearch` (ours, not `sklearn`) creates a grid with certain properties, not just a grid that is created by combining all options from all parameters with each other (which would be the Cartesian Product). [You may argue that that's not even a "grid" in the way most people think about it.]
One can either pass some of the information about what the grid should be like (including size as in number of grid points, and limits of the values in each dimensions) or directly pass a predefined grid. Since this isn't just a simple Cartesian Product I'm not entirely sure we can actually use `GridSearchCV` without a workaround. Is it possible to pass non-scalars (say, a column of the predefined grid) to `GridSearchCV`? Let's say the following:

```
args = {'grid' = [[1,0,0,0], [0,0,1,0], ...]}
```

If that works then we could define a small estimator that just does what `GridSearch` right now does, but with that one column vector (single `fit`) as opposed to a grid (`n` calls to `fit`), and then use `GridSearchCV` around the pipeline that contains that estimator.

`InterpolatedThresholder` is from postprocessing, so that's not directly related to this, but perhaps you were trying to point at something else?

**Comment by Dref360** [comment]
@romanlutz Should I go ahead with the PR while we wait for MiroDudik approval?

**Comment by MiroDudik** [comment]
If I understand correctly, the basic proposal here is to simply add a new keyword argument to the `GridSearch` constructor. Something like `sample_weight_name='sample_weight'`. I think we should go ahead! @Dref360 : From my perspective you can go ahead and start the PR.

@adrinjalali , @romanlutz , @riedgar-ms : We can pick up the discussion of whether we should get rid of `GridSearch` altogether and rely on `GridSearchCV` in a separate issue--I actually think it should be possible, but there are a few wrinkles to resolve (as @romanlutz is alluding to). Also, I agree with @adrinjalali that we should try to make our `ThresholdOptimizer` and `InterpolatedThresholder` plug into sklearn's pipelines (again a separate issue please).

**Comment by MiroDudik** [comment]
And I also agree with @romanlutz that we should add the same argument to `ExponentiatedGradient`, but that could be a separate PR.
