### ISSUE TITLE
Documentation doesn't list charts

### ISSUE THREAD

**Issue by koaning** [fairlearn/fairlearn#608]
When I go to the [a getting started page](https://fairlearn.github.io/auto_examples/plot_grid_search_census.html#training-a-fairness-unaware-predictor) I usually expect to see a full guide on how to use a library. Part of that is there, but ... there's no charts. In order to get the charts I need to run everything locally. This is a bummer of an experience, especially if you never worked with ipython widgets before. 

Wouldn't it be a lot more beginner-friendly just to show simple matplotlib charts in the docs?

**Comment by romanlutz** [comment]
Yes! This is related to https://github.com/fairlearn/fairlearn-proposals/blob/master/ui/migration.md . In short:
- The existing `FairlearnDashboard` will be migrated out of Fairlearn shortly (after the v0.5.0 release which will happen as soon as the metrics API is finalized) for reasons outlined in that link.
- At that point we'll complete #561 and update the documentation including the getting started page to show these plots instead. As you pointed out it's much better to have the plots actually render without having to download it first.

I'm hoping we can expand on these charts as well, since they provide very minimal functionality at this point. It's a good start, though! 

I think this issue is a good way to "track" the effort to update the docs after the `FairlearnDashboard` is removed, so I'd propose to leave it open. I'll assign it to myself since I promised to take care of the removal and docs update, but I'm very much looking for feedback on the resulting docs. I'll make sure to tag you on the PR(s).

Does this make sense @koaning ? Please keep the feedback & suggestions coming :-)

**Comment by romanlutz** [comment]
#770 and #766 are related to this. #770 is already completed and #766 will be shortly, at which point we can release v0.7.0 as the first version without dashboard.
