### ISSUE TITLE
 Widgets getting refreshed when different widgets are run

### ISSUE THREAD

**Issue by MarsLabAtSLU** [fairlearn/fairlearn#629]
I initially installed fairlearn using pip install.
The fair widget was working perfectly.

First I'd run the widget on the base model

from fairlearn.widget import FairlearnDashboard
FairlearnDashboard(sensitive_features=sex,
                   sensitive_feature_names=['sex'],
                   y_true=y_true,
                   y_pred={"initial model": y_pred}) 
Then I'd run the widget again on the mitigated model

from fairlearn.widget import FairlearnDashboard
FairlearnDashboard(sensitive_features=sex,
                   sensitive_feature_names=['sex'],
                   y_true=y_true,
                   y_pred={"mitigated model": y_pred_miitgated}) 
the default version using pip install, I was able to see two widgets one above the another and it was super helpful for comparison.

CHANGED BEHAVIOR AFTER INSTALLING FROM GIT
If I run the dashboard now with the mitigated output, the first dashboard also changes. Firstly, the widget does not show up in the cell below and only comes with open in new tab option

Also, the widget above that was displaying the y_pred, changes to start and while selecting them, it shows the new output. So no more comparison in the notebook.

This is not the behavior in the 0.4.7 version installed by pip

**Comment by MarsLabAtSLU** [comment]
@romanlutz Intended fix in progress. Pleas await for code changes.

**Comment by romanlutz** [comment]
@MarsLabAtSLU this was already reported in #593 . Since we're removing the widget and moving it to a dedicated visualization package called `raiwidgets` we've rolled back to the previous version of the widget. I'm certainly interested in your idea for a fix, since that may come in handy in the new repository (which will be public once `raiwidgets` is released, ETA end of November).

**Comment by MarsLabAtSLU** [comment]
@romanlutz sure will share my changes at the earliest.

**Comment by MarsLabAtSLU** [comment]
@romanlutz I’m trying to find the branch/tag where it-was-in the previous state which used "rai_core_flask FlaskHelper” in widget/Fairlearn_dashboard.py. So that, I can make my changes and raise Pull request. Could you please let me know.

**Comment by romanlutz** [comment]
@MarsLabAtSLU there was no tag/release version with flask since we rolled the change back before releasing. If you're looking for a specific version this one should work: https://github.com/fairlearn/fairlearn/tree/ce7f27a51a428dae7627c1eed6373fc4e626673f

Note that we will remove the entire dashboard from this repo shortly (I might do it today if I get to it) and it'll move to another repo, so a related PR in this repo won't be accepted because of that. If you have an idea for how to fix it feel free to outline it here or create a branch, though, since we still need to fix it regardless (just in another repo).

**Comment by romanlutz** [comment]
@MarsLabAtSLU There was an additional issue to fix. In case you are eager to build a dashboard manually in the meanwhile:

When running two dashboards with different ports they ran into a name collision of the functions with the `route` decorator. To fix that I defined the function without `route` decorator, renamed the function to be unique (by using the associated port below) and then applied `add_url_rule` manually instead of through the `route` decorator
```
def visual():
    ....
visual.__name__ = f"visual{self._service.port}"
self._service.app.add_url_rule('/', endpoint=visual.__name__, view_func=visual)
```
This has to be done for every function with a route decorator, including the one that is used to request metrics.

Since this is  
- neither a real issue the released dashboard is facing (since it's not on flask)
- nor will it become one for Fairlearn because the dashboard will be removed shortly
I am closing this issue and the associated pull request. 

Thanks @MarsLabAtSLU for your suggestion! Stay tuned for the upcoming release of `raiwidgets` which will provide a flask-based version of the fairness dashboard (and some new features).
