### ISSUE TITLE
Dashboard does not show up on Google Colab

### ISSUE THREAD

**Issue by amir78pgd** [fairlearn/fairlearn#639]
#### Steps/Code to Reproduce

```
Sample code to reproduce the problem
```

**Comment by romanlutz** [comment]
Colab is not explicitly supported. Note that after v0.5.0 the dashboard is moving to the new `raiwidgets` package (to be released by the end of the month). We're aiming to provide support for a broader set of environments (including Colab) in `raiwidgets`, although that may not happen at the time of the initial release.

Closing this issue since it won't be addressed in Fairlearn.
