### ISSUE TITLE
Request to host face benchmarking script on fairlearn

### ISSUE THREAD

**Issue by wguyman** [fairlearn/fairlearn#698]
Per recommendation from Richard Edgar, we're opening a new issue to propose hosting a python script on the fairlearn GitHub that allows developers to benchmark face recognition performance (measured by the same criteria used in industry such as NIST: True Positive, False Positive, and ROC curves) on their own data, using Azure Cognitive Services or other services and their own model. 

Pls let us know what process to follow. Thanks!

**Comment by riedgar-ms** [comment]
Rather than in the Fairlearn repo, this might work better as a separate repo in the Fairlearn org. The description above doesn't quite feel to me like something that fits in with the Fairlearn PyPI package itself.

Could you elaborate a bit on how you calculate fairness metrics on these recognisers, and what material you're providing to help users explore the fairness issues in these data @wguyman ? Do you actually use Fairlearn in your code?

Tagging @adrinjalali  and @hildeweerts who are our external maintainers, and can provide a non-Microsoft perspective.

**Comment by romanlutz** [comment]
I'd just like to echo what @riedgar-ms expressed. If this is focused on fairness analysis of such a system then I can see why hosting it under the Fairlearn org in a separate repo makes sense. It would definitely need some documentation to elaborate on fairness criteria, potential harms, etc. And finally, for new repos I think we'd want a certain commitment to maintain that repo. Not that I expect this to be a lot of work, but it's probably a non-zero effort.
Also adding @MiroDudik since he's on the steering committee which (I think?) makes such decisions.

**Comment by adrinjalali** [comment]
I'm not sure if the script using Azure Cognitive Services would be appropriate for this repo or org in general, but I find the idea of having scripts which would run certain benchmarks on datasets interesting.

I believe this falls under the category of having guidelines on certain use cases, or real world scenarios. We've talked about this before, and I know there's ample interest in the matter. However, it's rather tricky to define metrics against which we should test a dataset or a method since it depends on the use case and not only the dataset.

I'm sure @MiroDudik would have quite a bit to add on that.

**Comment by wguyman** [comment]
Thanks all! Yes, the plan is to publish fairness results of the service algorithms and then separately publish a python script customers can use on their own data that evaluates performance of cognitive services or other services across standard True Positive, False Positive, and ROC curves as used in the NIST report. 

The script doesn't use fairlearn code, so the question it sounds like is whether it could live in a different fairlearn repo?

**Comment by adrinjalali** [comment]
To me it sounds like a repo under the Microsoft org may be more suitable for this case?

**Comment by romanlutz** [comment]
Closing this issue. If there's any new information we should take into account please reopen! Thanks!
