### ISSUE TITLE
Support for by_group in Dashboard

### ISSUE THREAD

**Issue by michaelamoako** [fairlearn/fairlearn#759]
#### Is your feature request related to a problem? Please describe.
by_group currently supported in MetricFrame, but not yet in Dashboard.

#### Describe the solution you'd like
Ability to select multiple sensitive features in dashboard, and view results across intersections

#### Describe alternatives you've considered, if relevant
API 

#### Additional context
Users of the notebook will likely want to use the dashboard

**Comment by romanlutz** [comment]
@michaelamoako the `FairlearnDashboard` in Fairlearn is deprecated and will be deleted shortly. Are you referring to the `FairnessDashboard` in `raiwidgets`? If so, this sounds like a feature request for [that repo](https://github.com/microsoft/responsible-ai-widgets) rather than Fairlearn.

Fairlearn is adding plotting functionality at the moment and multiple sensitive feature support is on our radar for that. The corresponding PR is #561

**Comment by adrinjalali** [comment]
Yep, dashboard issues are out of scope for this repo now.
