### ISSUE TITLE
Support different costs for false positives and false negatives in ExponentiatedGradient

### ISSUE THREAD

**Issue by MiroDudik** [fairlearn/fairlearn#804]
#### Is your feature request related to a problem? Please describe.

In many binary classification problems, the costs of false positives do not equal to the costs of false negatives, but our `ExponentiatedGradient` only allows classification accuracy as the objective, which assumes that these costs are equal.

#### Describe the solution you'd like

We should extend the moment `ErrorRate` to allow for asymmetric costs, and also allow specifying these costs in the constructor to `ExponentiatedGradient`.

I'm thinking that there are two natural API choices. Say, we're considering fairness under demographic parity and the costs for false positives and false negatives are 1.0 and 0.1. Then:

```python
# Current API, which does not allow specifying asymmetric costs for the objective:
expgrad = ExponentiatedGradient(
    learner,
    constraints=DemographicParity())

# API idea (1): Allow specifying the objective via a moment object
expgrad = ExponentiatedGradient(
    learner,
    constraints=DemographicParity(),
    objective=ErrorRate(costs={'fn': 1.0, 'fp': 0.1}))

# API idea (2): Specify the objective costs more directly
expgrad = ExponentiatedGradient(
    learner,
    constraints=DemographicParity(),
    objective_costs={'fn': 1.0, 'fp': 0.1})
```
I slightly prefer API (1), because it allows for extensions into future in case we want to support other objective functions.

The API (2) is a bit simpler and matches #473, but it could be a bit confusing, because `objective_costs` would not be applicable when we are using `ExponentiatedGradient` for regression.

**Comment by MiroDudik** [comment]
@fairlearn/fairlearn-maintainers : This would be nice to have for the scipy-tutorial. I have this already implemented and will create a PR shortly, but I'd like to get a sense what you think the API should be.

**Comment by romanlutz** [comment]
Perhaps I'm misremembering but isn't cost represented as a Moment (ErrorRate?) as well? In that case just make it optional with default ErrorRate and this feature would be accommodated through arguments to that Moment. For regression it would be some other Moment presumably (?)

Specifying the objective in the API makes sense to me since we do that in postprocessing. We only use strings there, but that has its own limitations. For example, I can't plug in F1 score even though there's no particularly good reason why I shouldn't. If it's a Moment I can write one custom for my case. Definitely not the primary concern, though.

**Comment by MiroDudik** [comment]
@romanlutz -- yep, this was also my sentiment. Let's go with providing the objective as a moment object. Then the question is whether we should be existing the existing `ErrorRate` moment or creating a new moment with this functionality and if so what should be the name of the new moment and the mechanism of providing different costs. Some possibilities:

```python
# should we extend ErrorRate?
objective = ErrorRate(costs={'fn': 1.0, 'fp': 0.1}) 

# or create a new moment?
objective = CostSensitiveLoss(costs={'fn': 1.0, 'fp': 0.1})
```

**Comment by MiroDudik** [comment]
Ping @romanlutz and @riedgar-ms: `ErrorRate` or `CostSensitiveLoss`? (I started the PR with the former, but it would be easy to tweak to the latter.)

**Comment by romanlutz** [comment]
What's wrong with ErrorRate? Indeed I wasn't sure cost sensitive loss is for classification.

**Comment by hildeweerts** [comment]
Not sure if this is relevant, but in scikit-learn the `class_weight` argument is typically used to define different costs per class, in the form of a dictionary with different weight for each class. If we ever wanted to extend `ExponentiatedGradient` to a multi class classification scenario, the current proposal would be more difficult to extend without breaking existing code.

**Comment by riedgar-ms** [comment]
Responding to a ping....  since we already have `ErrorRate` I'd be happy with going with option (1), and just adding an optional `costs=` argument to the constructor.

To @hildeweerts 's concern, I think that a multiclass extension could be a separate moment - you'd have to specify a full matrix of costs. Although our docs would naturally point out the equivalent matrix to the `ErrorRate` case. Indeed `CostSensitiveLoss` could be a good name for that multi-class moment.
