### ISSUE TITLE
DOC: multi-version behaves weird on example notebooks

### ISSUE THREAD

**Issue by hildeweerts** [fairlearn/fairlearn#874]
#### Describe the issue linked to the documentation

When you go to the [example notebooks](https://fairlearn.org/main/auto_examples/index.html) page, it always shows whatever version you had previously selected and "Documentation page not present" for the other versions. This makes it impossible to switch versions once you're on the Example Notebooks page.

Examples:

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/24417440/123223339-1cb7e800-d4d1-11eb-83b7-4ec15a57f9a3.png">
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/24417440/123223381-23def600-d4d1-11eb-8c18-70f041cc5d45.png">

#### Suggest a potential alternative/fix
The preferred behavior would be that one is able to click on the other versions on the Example Notebooks page.

I'm not really sure why this happens but I'm assuming that there is some issue with the way `sphinx-gallery` and `sphinx-multiversion` work together.

**Comment by romanlutz** [comment]
Your assessment is correct @hildeweerts! @riedgar-ms filed an issue for this with sphinx-multiversion. I'm starting to wonder whether we'd be better off not using sphinx-multiversion and instead follow the approach scikit-learn uses. If I understand correctly that would involve building the doc pages separately and inserting a common nav part on each page with which one can move to the other versions (although only to the landing page of the other versions, not to the exact same page in a different version since that may not even exist). Is that an accurate description @adrinjalali ?

**Comment by adrinjalali** [comment]
Yes, that's correct. You independently would build the docs for different versions, which also makes a few things easier for us (like removing dependencies)

**Comment by romanlutz** [comment]
This is now fixed since we stopped using sphinx-multiversion! I tried it with https://fairlearn.org/main/auto_examples/plot_quickstart_selection_rate.html and it worked fine, at least between latest and stable. Beyond that, the old pages have the same issue because they were built with multiversion, but that's fine. Over time we'll get rid of them anyway...
