### ISSUE TITLE
ENH: Incorporating folktables datasets from Ding et al.

### ISSUE THREAD

**Issue by millerjohnp** [fairlearn/fairlearn#984]
#### Is your feature request related to a problem? Please describe.

Fairlearn currently exposes and makes use of the UCI Adult dataset in a few places, e.g. [in this example](https://github.com/fairlearn/fairlearn/blob/1247b081b5cbdf9373595b7e4627c142ae30ae44/examples/plot_grid_search_census.py). (Some recent work)[https://arxiv.org/abs/2108.04884] I've been apart of has highlighted a few limitations with UCI Adult and introduced a [few new datasets](https://github.com/zykls/folktables) for fair ML intended to serve as a replacement.

I discussed this briefly with @romanlutz, and I'd love to find a way to incorporate these datasets into fairlearn, perhaps as a dedicated example or as a replacement to UCI Adult in the current example. I'm happy to do most or all of the implementation work needed to make something like that happen, but I first wanted to discuss with the maintainers or others involved with the project what the best way of incorporating these datasets would be. 

Looking forward to discussing.

**Comment by adrinjalali** [comment]
I just came to say what @hildeweerts said.

**Comment by romanlutz** [comment]
Thanks for submitting this issue @millerjohnp! 

I'm very much in favor of this project since we're not doing a good job at providing the information on why this dataset may not be ideal to use as a benchmark. Of course, your paper (and repo) add several alternative datasets which could be added to `fairlearn.datasets`. More on that below.

I'd also encourage breaking it down into as many pieces as possible. In my own experience (see many PRs of mine) it's a lot easier to add a small change/addition rather than a big chunk since all reviewers need to be satisfied and the more content there is the more there is to disagree on.

I see several pieces here:
- documenting the existing Adult dataset - all we have right now is https://fairlearn.org/main/api_reference/fairlearn.datasets.html#fairlearn.datasets.fetch_adult . A more elaborate exploration would probably go into the user guide. 
- Uploading the new datasets to OpenML
- Adding functions to the `datasets` module to import the OpenML datasets with a basic docstring
- Adding context on why these new datasets are in some ways preferable to the existing adult dataset either in the user guide or through an example.

Note: #961 is currently adding a datasets section in the user guide to which some of this could be added.

I would be a bit reluctant to replace the adult dataset in the "get started" guide because we were planning to use a synthetic dataset there, based on #907. The rationale in short is that when you don't have the time to explain the context, don't use the data. In user guide or examples we do have the space to elaborate, so it's different there.

**Comment by romanlutz** [comment]
@millerjohnp did you have any success with OpenML?

We may have people willing to capture the most important information from the paper regarding the original Adult dataset and the new datasets in a section of the user guide as mentioned in my previous post here. If the datasets are on OpenML we can directly use them from there, otherwise we'll perhaps try to upload them ourselves. Let me know 🙂

**Comment by millerjohnp** [comment]
Hey @romanlutz apologies for the delay here. I've been distracted by other projects the last few months. I have some time right after the ICML deadline to update the documentation for the Adult dataset and also finish uploading our datasets to OpenML so they're usable in fairlearn. Thanks for your patience :)

**Comment by romanlutz** [comment]
No worries! @kspieks and @britneyting will probably try to come up with a first version of a documentation through the user guide. This should be based on the findings in your paper, of course, but may also include other information.

I believe the ICML deadline is end of January, right? It would be great if you could provide feedback or make additions at that point. Of course, you're more than welcome to join our community call (every Thursday, 8am PT) on [Discord](https://discord.gg/R22yCfgsRn) to discuss further. Good luck with your deadline and I'm looking forward to getting this effort off the ground 🙂

**Comment by hildeweerts** [comment]
Agreed, I'm closing this issue @TamaraAtanasoska.

@romanlutz please feel free to reopen if you feel differently!
